var EntityLogicalName = "msdyn_agreement";
var Form_8f5d9b5f_49b2_4d80_81c9_f080fe4301c0_Properties = {
msdyn_agreementdetails: "msdyn_agreementdetails"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_datecanceled: "msdyn_datecanceled"
,msdyn_description: "msdyn_description"
,msdyn_duration: "msdyn_duration"
,msdyn_enddate: "msdyn_enddate"
,msdyn_name: "msdyn_name"
,msdyn_originatingagreement: "msdyn_originatingagreement"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_salestaxcode: "msdyn_salestaxcode"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_serviceterritory: "msdyn_serviceterritory"
,msdyn_startdate: "msdyn_startdate"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,ownerid: "ownerid"
};

var Form_8f5d9b5f_49b2_4d80_81c9_f080fe4301c0_Controls = {
bookingsgrid: "bookingsgrid"
,invoicegrid: "invoicegrid"
,msdyn_agreementdetails: "msdyn_agreementdetails"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_datecanceled: "msdyn_datecanceled"
,msdyn_description: "msdyn_description"
,msdyn_duration: "msdyn_duration"
,msdyn_enddate: "msdyn_enddate"
,msdyn_name: "msdyn_name"
,msdyn_originatingagreement: "msdyn_originatingagreement"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_salestaxcode: "msdyn_salestaxcode"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_serviceterritory: "msdyn_serviceterritory"
,msdyn_startdate: "msdyn_startdate"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
};

