var EntityLogicalName = "msdyn_agreement";
var Form_d3fab127_1057_4b53_99a2_f38b90877e99_Properties = {
msdyn_agreementdetails: "msdyn_agreementdetails"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_datecanceled: "msdyn_datecanceled"
,msdyn_description: "msdyn_description"
,msdyn_duration: "msdyn_duration"
,msdyn_enddate: "msdyn_enddate"
,msdyn_name: "msdyn_name"
,msdyn_originatingagreement: "msdyn_originatingagreement"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_salestaxcode: "msdyn_salestaxcode"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_serviceterritory: "msdyn_serviceterritory"
,msdyn_startdate: "msdyn_startdate"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,ownerid: "ownerid"
};

var Form_d3fab127_1057_4b53_99a2_f38b90877e99_Controls = {
bookingsgrid: "bookingsgrid"
,ContractLines: "ContractLines"
,header_msdyn_name: "header_msdyn_name"
,header_msdyn_serviceaccount: "header_msdyn_serviceaccount"
,header_ownerid: "header_ownerid"
,invoicegrid: "invoicegrid"
,msdyn_agreementdetails: "msdyn_agreementdetails"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_datecanceled: "msdyn_datecanceled"
,msdyn_description: "msdyn_description"
,msdyn_duration: "msdyn_duration"
,msdyn_enddate: "msdyn_enddate"
,msdyn_name: "msdyn_name"
,msdyn_originatingagreement: "msdyn_originatingagreement"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_salestaxcode: "msdyn_salestaxcode"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_serviceterritory: "msdyn_serviceterritory"
,msdyn_startdate: "msdyn_startdate"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,QuotesLinesGrid: "QuotesLinesGrid"
};

