var EntityLogicalName = "msdyn_agreementbookingsetup";
var Form_43ba8f00_d25b_45b7_89d4_52a658cc62bf_Properties = {
msdyn_agreement: "msdyn_agreement"
,msdyn_autogeneratebooking: "msdyn_autogeneratebooking"
,msdyn_autogeneratewo: "msdyn_autogeneratewo"
,msdyn_description: "msdyn_description"
,msdyn_estimatedduration: "msdyn_estimatedduration"
,msdyn_generatewodaysinadvance: "msdyn_generatewodaysinadvance"
,msdyn_name: "msdyn_name"
,msdyn_postbookingflexibility: "msdyn_postbookingflexibility"
,msdyn_prebookingflexibility: "msdyn_prebookingflexibility"
,msdyn_preferredresource: "msdyn_preferredresource"
,msdyn_preferredstarttime: "msdyn_preferredstarttime"
,msdyn_priority: "msdyn_priority"
,msdyn_recurrencesettings: "msdyn_recurrencesettings"
,msdyn_timewindowend: "msdyn_timewindowend"
,msdyn_timewindowstart: "msdyn_timewindowstart"
,msdyn_workordersummary: "msdyn_workordersummary"
,msdyn_workordertype: "msdyn_workordertype"
,ownerid: "ownerid"
,statecode: "statecode"
};

var Form_43ba8f00_d25b_45b7_89d4_52a658cc62bf_Controls = {
AgreementBookingProductsGrid: "AgreementBookingProductsGrid"
,AgreementBookingServicesGrid: "AgreementBookingServicesGrid"
,AgreementBookingServiceTasksGrid: "AgreementBookingServiceTasksGrid"
,footer_statecode: "footer_statecode"
,incidentsgrid: "incidentsgrid"
,msdyn_agreement: "msdyn_agreement"
,msdyn_autogeneratebooking: "msdyn_autogeneratebooking"
,msdyn_autogeneratewo: "msdyn_autogeneratewo"
,msdyn_description: "msdyn_description"
,msdyn_estimatedduration: "msdyn_estimatedduration"
,msdyn_generatewodaysinadvance: "msdyn_generatewodaysinadvance"
,msdyn_name: "msdyn_name"
,msdyn_postbookingflexibility: "msdyn_postbookingflexibility"
,msdyn_prebookingflexibility: "msdyn_prebookingflexibility"
,msdyn_preferredresource: "msdyn_preferredresource"
,msdyn_preferredstarttime: "msdyn_preferredstarttime"
,msdyn_priority: "msdyn_priority"
,msdyn_recurrencesettings: "msdyn_recurrencesettings"
,msdyn_timewindowend: "msdyn_timewindowend"
,msdyn_timewindowstart: "msdyn_timewindowstart"
,msdyn_workordersummary: "msdyn_workordersummary"
,msdyn_workordertype: "msdyn_workordertype"
,ownerid: "ownerid"
,schecduledategrid: "schecduledategrid"
,WebResource_PreferredStartTime_TimeField: "WebResource_PreferredStartTime_TimeField"
,WebResource_TimeWindowEnd_TimeField: "WebResource_TimeWindowEnd_TimeField"
,WebResource_TimeWindowStart_TimeField: "WebResource_TimeWindowStart_TimeField"
};

