var EntityLogicalName = "msdyn_agreementbookingsetup";
var Form_2ed8ae97_4c5d_45cb_9c11_21400fd9e6d4_Properties = {
msdyn_agreement: "msdyn_agreement"
,msdyn_autogeneratebooking: "msdyn_autogeneratebooking"
,msdyn_autogeneratewo: "msdyn_autogeneratewo"
,msdyn_description: "msdyn_description"
,msdyn_estimatedduration: "msdyn_estimatedduration"
,msdyn_generatewodaysinadvance: "msdyn_generatewodaysinadvance"
,msdyn_name: "msdyn_name"
,msdyn_postbookingflexibility: "msdyn_postbookingflexibility"
,msdyn_prebookingflexibility: "msdyn_prebookingflexibility"
,msdyn_preferredresource: "msdyn_preferredresource"
,msdyn_preferredstarttime: "msdyn_preferredstarttime"
,msdyn_priority: "msdyn_priority"
,msdyn_recurrencesettings: "msdyn_recurrencesettings"
,msdyn_timewindowend: "msdyn_timewindowend"
,msdyn_timewindowstart: "msdyn_timewindowstart"
,msdyn_workordersummary: "msdyn_workordersummary"
,msdyn_workordertype: "msdyn_workordertype"
,ownerid: "ownerid"
};

var Form_2ed8ae97_4c5d_45cb_9c11_21400fd9e6d4_Controls = {
AgreementBookingProductsGrid: "AgreementBookingProductsGrid"
,AgreementBookingServicesGrid: "AgreementBookingServicesGrid"
,AgreementBookingServiceTasksGrid: "AgreementBookingServiceTasksGrid"
,incidentsgrid: "incidentsgrid"
,msdyn_agreement: "msdyn_agreement"
,msdyn_autogeneratebooking: "msdyn_autogeneratebooking"
,msdyn_autogeneratewo: "msdyn_autogeneratewo"
,msdyn_description: "msdyn_description"
,msdyn_estimatedduration: "msdyn_estimatedduration"
,msdyn_generatewodaysinadvance: "msdyn_generatewodaysinadvance"
,msdyn_name: "msdyn_name"
,msdyn_postbookingflexibility: "msdyn_postbookingflexibility"
,msdyn_prebookingflexibility: "msdyn_prebookingflexibility"
,msdyn_preferredresource: "msdyn_preferredresource"
,msdyn_preferredstarttime: "msdyn_preferredstarttime"
,msdyn_priority: "msdyn_priority"
,msdyn_recurrencesettings: "msdyn_recurrencesettings"
,msdyn_timewindowend: "msdyn_timewindowend"
,msdyn_timewindowstart: "msdyn_timewindowstart"
,msdyn_workordersummary: "msdyn_workordersummary"
,msdyn_workordertype: "msdyn_workordertype"
,ownerid: "ownerid"
,schecduledategrid: "schecduledategrid"
,WebResource_PreferredStartTime_TimeField: "WebResource_PreferredStartTime_TimeField"
,WebResource_TimeWindowEnd_TimeField: "WebResource_TimeWindowEnd_TimeField"
,WebResource_TimeWindowStart_TimeField: "WebResource_TimeWindowStart_TimeField"
};

