var EntityLogicalName = "bookableresource";
var Form_7be43c5d_9556_4f96_a028_6e8d0c2ff940_Properties = {
accountid: "accountid"
,contactid: "contactid"
,msdyn_bookingstodrip: "msdyn_bookingstodrip"
,msdyn_displayonscheduleassistant: "msdyn_displayonscheduleassistant"
,msdyn_displayonscheduleboard: "msdyn_displayonscheduleboard"
,msdyn_enabledripscheduling: "msdyn_enabledripscheduling"
,msdyn_endlocation: "msdyn_endlocation"
,msdyn_generictype: "msdyn_generictype"
,msdyn_hourlyrate: "msdyn_hourlyrate"
,msdyn_startlocation: "msdyn_startlocation"
,msdyn_timeoffapprovalrequired: "msdyn_timeoffapprovalrequired"
,msdyn_warehouse: "msdyn_warehouse"
,name: "name"
,resourcetype: "resourcetype"
,timezone: "timezone"
,userid: "userid"
};

var Form_7be43c5d_9556_4f96_a028_6e8d0c2ff940_Controls = {
accountid: "accountid"
,BookableResourceCharacteristics: "BookableResourceCharacteristics"
,CATEGORYASSOCIATIONS: "CATEGORYASSOCIATIONS"
,contactid: "contactid"
,msdyn_bookingstodrip: "msdyn_bookingstodrip"
,msdyn_displayonscheduleassistant: "msdyn_displayonscheduleassistant"
,msdyn_displayonscheduleboard: "msdyn_displayonscheduleboard"
,msdyn_enabledripscheduling: "msdyn_enabledripscheduling"
,msdyn_endlocation: "msdyn_endlocation"
,msdyn_generictype: "msdyn_generictype"
,msdyn_hourlyrate: "msdyn_hourlyrate"
,msdyn_startlocation: "msdyn_startlocation"
,msdyn_timeoffapprovalrequired: "msdyn_timeoffapprovalrequired"
,msdyn_warehouse: "msdyn_warehouse"
,name: "name"
,notescontrol: "notescontrol"
,ResourceCategory: "ResourceCategory"
,ResourceCharacteristics: "ResourceCharacteristics"
,resourcetype: "resourcetype"
,timezone: "timezone"
,userid: "userid"
};

