var EntityLogicalName = "bookableresource";
var Form_3e8942a7_ff8e_4634_84ec_8ce174ab807c_Properties = {
accountid: "accountid"
,contactid: "contactid"
,msdyn_bookingstodrip: "msdyn_bookingstodrip"
,msdyn_displayonscheduleassistant: "msdyn_displayonscheduleassistant"
,msdyn_displayonscheduleboard: "msdyn_displayonscheduleboard"
,msdyn_enabledripscheduling: "msdyn_enabledripscheduling"
,msdyn_endlocation: "msdyn_endlocation"
,msdyn_generictype: "msdyn_generictype"
,msdyn_hourlyrate: "msdyn_hourlyrate"
,msdyn_organizationalunit: "msdyn_organizationalunit"
,msdyn_startlocation: "msdyn_startlocation"
,msdyn_targetutilization: "msdyn_targetutilization"
,msdyn_timeoffapprovalrequired: "msdyn_timeoffapprovalrequired"
,msdyn_warehouse: "msdyn_warehouse"
,name: "name"
,resourcetype: "resourcetype"
,timezone: "timezone"
,userid: "userid"
};

var Form_3e8942a7_ff8e_4634_84ec_8ce174ab807c_Controls = {
accountid: "accountid"
,BookableResourceCharacteristics: "BookableResourceCharacteristics"
,CATEGORYASSOCIATIONS: "CATEGORYASSOCIATIONS"
,contactid: "contactid"
,msdyn_bookingstodrip: "msdyn_bookingstodrip"
,msdyn_displayonscheduleassistant: "msdyn_displayonscheduleassistant"
,msdyn_displayonscheduleboard: "msdyn_displayonscheduleboard"
,msdyn_enabledripscheduling: "msdyn_enabledripscheduling"
,msdyn_endlocation: "msdyn_endlocation"
,msdyn_generictype: "msdyn_generictype"
,msdyn_hourlyrate: "msdyn_hourlyrate"
,msdyn_organizationalunit: "msdyn_organizationalunit"
,msdyn_startlocation: "msdyn_startlocation"
,msdyn_targetutilization: "msdyn_targetutilization"
,msdyn_timeoffapprovalrequired: "msdyn_timeoffapprovalrequired"
,msdyn_warehouse: "msdyn_warehouse"
,name: "name"
,notescontrol: "notescontrol"
,ResourceCategory: "ResourceCategory"
,ResourceCharacteristics: "ResourceCharacteristics"
,ResourceRole: "ResourceRole"
,Resourceskills: "Resourceskills"
,resourcetype: "resourcetype"
,timezone: "timezone"
,userid: "userid"
};

