var EntityLogicalName = "bookableresourcebooking";
var Form_396ccc86_fa22_4351_8cc5_83d8cf209720_Properties = {
bookingstatus: "bookingstatus"
,bookingtype: "bookingtype"
,duration: "duration"
,endtime: "endtime"
,msdyn_actualarrivaltime: "msdyn_actualarrivaltime"
,msdyn_actualtravelduration: "msdyn_actualtravelduration"
,msdyn_agreementbookingdate: "msdyn_agreementbookingdate"
,msdyn_allowoverlapping: "msdyn_allowoverlapping"
,msdyn_bookingmethod: "msdyn_bookingmethod"
,msdyn_estimatedarrivaltime: "msdyn_estimatedarrivaltime"
,msdyn_estimatedtravelduration: "msdyn_estimatedtravelduration"
,msdyn_latitude: "msdyn_latitude"
,msdyn_longitude: "msdyn_longitude"
,msdyn_milestraveled: "msdyn_milestraveled"
,msdyn_resourcegroup: "msdyn_resourcegroup"
,msdyn_signature: "msdyn_signature"
,msdyn_timegroupdetailselected: "msdyn_timegroupdetailselected"
,msdyn_totalbillableduration: "msdyn_totalbillableduration"
,msdyn_totalbreakduration: "msdyn_totalbreakduration"
,msdyn_totalcost: "msdyn_totalcost"
,msdyn_totaldurationinprogress: "msdyn_totaldurationinprogress"
,msdyn_workorder: "msdyn_workorder"
,name: "name"
,resource: "resource"
,starttime: "starttime"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_396ccc86_fa22_4351_8cc5_83d8cf209720_Controls = {
bookingstatus: "bookingstatus"
,bookingtype: "bookingtype"
,duration: "duration"
,endtime: "endtime"
,msdyn_actualarrivaltime: "msdyn_actualarrivaltime"
,msdyn_actualtravelduration: "msdyn_actualtravelduration"
,msdyn_agreementbookingdate: "msdyn_agreementbookingdate"
,msdyn_allowoverlapping: "msdyn_allowoverlapping"
,msdyn_bookingmethod: "msdyn_bookingmethod"
,msdyn_estimatedarrivaltime: "msdyn_estimatedarrivaltime"
,msdyn_estimatedtravelduration: "msdyn_estimatedtravelduration"
,msdyn_latitude: "msdyn_latitude"
,msdyn_longitude: "msdyn_longitude"
,msdyn_milestraveled: "msdyn_milestraveled"
,msdyn_resourcegroup: "msdyn_resourcegroup"
,msdyn_signature: "msdyn_signature"
,msdyn_timegroupdetailselected: "msdyn_timegroupdetailselected"
,msdyn_totalbillableduration: "msdyn_totalbillableduration"
,msdyn_totalbreakduration: "msdyn_totalbreakduration"
,msdyn_totalcost: "msdyn_totalcost"
,msdyn_totaldurationinprogress: "msdyn_totaldurationinprogress"
,msdyn_workorder: "msdyn_workorder"
,name: "name"
,notescontrol: "notescontrol"
,PRODUCTS: "PRODUCTS"
,resource: "resource"
,SERVICE_TASKS: "SERVICE_TASKS"
,SERVICES: "SERVICES"
,starttime: "starttime"
,transactioncurrencyid: "transactioncurrencyid"
};

