var EntityLogicalName = "bookableresourcebooking";
var Form_8be6de4f_d6c3_4633_ac5d_92160e4b70bb_Properties = {
bookingstatus: "bookingstatus"
,bookingtype: "bookingtype"
,duration: "duration"
,endtime: "endtime"
,msdyn_actualarrivaltime: "msdyn_actualarrivaltime"
,msdyn_actualtravelduration: "msdyn_actualtravelduration"
,msdyn_agreementbookingdate: "msdyn_agreementbookingdate"
,msdyn_allowoverlapping: "msdyn_allowoverlapping"
,msdyn_bookingmethod: "msdyn_bookingmethod"
,msdyn_estimatedarrivaltime: "msdyn_estimatedarrivaltime"
,msdyn_estimatedtravelduration: "msdyn_estimatedtravelduration"
,msdyn_latitude: "msdyn_latitude"
,msdyn_longitude: "msdyn_longitude"
,msdyn_milestraveled: "msdyn_milestraveled"
,msdyn_resourcegroup: "msdyn_resourcegroup"
,msdyn_resourcerequirement: "msdyn_resourcerequirement"
,msdyn_timegroupdetailselected: "msdyn_timegroupdetailselected"
,msdyn_totalbillableduration: "msdyn_totalbillableduration"
,msdyn_totalbreakduration: "msdyn_totalbreakduration"
,msdyn_totalcost: "msdyn_totalcost"
,msdyn_totaldurationinprogress: "msdyn_totaldurationinprogress"
,msdyn_workorder: "msdyn_workorder"
,name: "name"
,resource: "resource"
,starttime: "starttime"
};

var Form_8be6de4f_d6c3_4633_ac5d_92160e4b70bb_Controls = {
bookingstatus: "bookingstatus"
,bookingtype: "bookingtype"
,duration: "duration"
,endtime: "endtime"
,msdyn_actualarrivaltime: "msdyn_actualarrivaltime"
,msdyn_actualtravelduration: "msdyn_actualtravelduration"
,msdyn_agreementbookingdate: "msdyn_agreementbookingdate"
,msdyn_allowoverlapping: "msdyn_allowoverlapping"
,msdyn_bookingmethod: "msdyn_bookingmethod"
,msdyn_estimatedarrivaltime: "msdyn_estimatedarrivaltime"
,msdyn_estimatedtravelduration: "msdyn_estimatedtravelduration"
,msdyn_latitude: "msdyn_latitude"
,msdyn_longitude: "msdyn_longitude"
,msdyn_milestraveled: "msdyn_milestraveled"
,msdyn_resourcegroup: "msdyn_resourcegroup"
,msdyn_resourcerequirement: "msdyn_resourcerequirement"
,msdyn_timegroupdetailselected: "msdyn_timegroupdetailselected"
,msdyn_totalbillableduration: "msdyn_totalbillableduration"
,msdyn_totalbreakduration: "msdyn_totalbreakduration"
,msdyn_totalcost: "msdyn_totalcost"
,msdyn_totaldurationinprogress: "msdyn_totaldurationinprogress"
,msdyn_workorder: "msdyn_workorder"
,name: "name"
,notescontrol: "notescontrol"
,resource: "resource"
,starttime: "starttime"
,TIMESTAMPS: "TIMESTAMPS"
};

