var EntityLogicalName = "businessunit";
var Form_ca8dfced_338c_43b2_b212_83745e257c28_Properties = {
address1_city: "address1_city"
,address1_country: "address1_country"
,address1_line1: "address1_line1"
,address1_line2: "address1_line2"
,address1_line3: "address1_line3"
,address1_postalcode: "address1_postalcode"
,address1_stateorprovince: "address1_stateorprovince"
,address1_telephone1: "address1_telephone1"
,address1_telephone2: "address1_telephone2"
,address1_telephone3: "address1_telephone3"
,address2_city: "address2_city"
,address2_country: "address2_country"
,address2_line1: "address2_line1"
,address2_line2: "address2_line2"
,address2_line3: "address2_line3"
,address2_postalcode: "address2_postalcode"
,address2_stateorprovince: "address2_stateorprovince"
,divisionname: "divisionname"
,emailaddress: "emailaddress"
,name: "name"
,parentbusinessunitid: "parentbusinessunitid"
,websiteurl: "websiteurl"
};

var Form_ca8dfced_338c_43b2_b212_83745e257c28_Controls = {
address1_city: "address1_city"
,address1_country: "address1_country"
,address1_line1: "address1_line1"
,address1_line2: "address1_line2"
,address1_line3: "address1_line3"
,address1_postalcode: "address1_postalcode"
,address1_stateorprovince: "address1_stateorprovince"
,address1_telephone1: "address1_telephone1"
,address1_telephone2: "address1_telephone2"
,address1_telephone3: "address1_telephone3"
,address2_city: "address2_city"
,address2_country: "address2_country"
,address2_line1: "address2_line1"
,address2_line2: "address2_line2"
,address2_line3: "address2_line3"
,address2_postalcode: "address2_postalcode"
,address2_stateorprovince: "address2_stateorprovince"
,divisionname: "divisionname"
,emailaddress: "emailaddress"
,name: "name"
,parentbusinessunitid: "parentbusinessunitid"
,websiteurl: "websiteurl"
};

