var EntityLogicalName = "campaignactivity";
var Form_30b5a041_afe1_4ced_91c5_86c7554df10c_Properties = {
actualcost: "actualcost"
,actualend: "actualend"
,actualstart: "actualstart"
,budgetedcost: "budgetedcost"
,channeltypecode: "channeltypecode"
,description: "description"
,excludeifcontactedinxdays: "excludeifcontactedinxdays"
,ownerid: "ownerid"
,partners: "partners"
,prioritycode: "prioritycode"
,regardingobjectid: "regardingobjectid"
,scheduledend: "scheduledend"
,scheduledstart: "scheduledstart"
,statuscode: "statuscode"
,subject: "subject"
,transactioncurrencyid: "transactioncurrencyid"
,typecode: "typecode"
};

var Form_30b5a041_afe1_4ced_91c5_86c7554df10c_Controls = {
actualcost: "actualcost"
,actualend: "actualend"
,actualstart: "actualstart"
,budgetedcost: "budgetedcost"
,channeltypecode: "channeltypecode"
,description: "description"
,excludeifcontactedinxdays: "excludeifcontactedinxdays"
,header_ownerid: "header_ownerid"
,header_prioritycode: "header_prioritycode"
,header_statuscode: "header_statuscode"
,marketing_lists_grid: "marketing_lists_grid"
,notescontrol: "notescontrol"
,partners: "partners"
,regardingobjectid: "regardingobjectid"
,scheduledend: "scheduledend"
,scheduledstart: "scheduledstart"
,statuscode: "statuscode"
,subject: "subject"
,transactioncurrencyid: "transactioncurrencyid"
,typecode: "typecode"
};

