var EntityLogicalName = "campaign";
var Form_6356ff2a_bbbe_49fb_9da2_160b08865688_Properties = {
actualend: "actualend"
,actualstart: "actualstart"
,budgetedcost: "budgetedcost"
,codename: "codename"
,createdon: "createdon"
,description: "description"
,expectedresponse: "expectedresponse"
,expectedrevenue: "expectedrevenue"
,istemplate: "istemplate"
,modifiedby: "modifiedby"
,modifiedon: "modifiedon"
,name: "name"
,objective: "objective"
,othercost: "othercost"
,ownerid: "ownerid"
,proposedend: "proposedend"
,proposedstart: "proposedstart"
,statuscode: "statuscode"
,totalactualcost: "totalactualcost"
,totalcampaignactivityactualcost: "totalcampaignactivityactualcost"
,transactioncurrencyid: "transactioncurrencyid"
,typecode: "typecode"
};

var Form_6356ff2a_bbbe_49fb_9da2_160b08865688_Controls = {
Activities: "Activities"
,actualend: "actualend"
,actualstart: "actualstart"
,budgetedcost: "budgetedcost"
,codename: "codename"
,createdon: "createdon"
,description: "description"
,expectedresponse: "expectedresponse"
,header_expectedrevenue: "header_expectedrevenue"
,header_istemplate: "header_istemplate"
,header_ownerid: "header_ownerid"
,header_statuscode: "header_statuscode"
,Leads: "Leads"
,Lists: "Lists"
,modifiedby: "modifiedby"
,modifiedon: "modifiedon"
,name: "name"
,notescontrol: "notescontrol"
,objective: "objective"
,othercost: "othercost"
,ownerid: "ownerid"
,proposedend: "proposedend"
,proposedstart: "proposedstart"
,Responses: "Responses"
,totalactualcost: "totalactualcost"
,totalcampaignactivityactualcost: "totalcampaignactivityactualcost"
,transactioncurrencyid: "transactioncurrencyid"
,typecode: "typecode"
};

