var EntityLogicalName = "campaign";
var Form_88de0f86_b850_4dad_9751_c2b8437f2625_Properties = {
actualend: "actualend"
,actualstart: "actualstart"
,budgetedcost: "budgetedcost"
,codename: "codename"
,createdon: "createdon"
,description: "description"
,expectedresponse: "expectedresponse"
,expectedrevenue: "expectedrevenue"
,modifiedby: "modifiedby"
,modifiedon: "modifiedon"
,name: "name"
,objective: "objective"
,othercost: "othercost"
,ownerid: "ownerid"
,pricelistid: "pricelistid"
,proposedend: "proposedend"
,proposedstart: "proposedstart"
,statuscode: "statuscode"
,totalactualcost: "totalactualcost"
,totalcampaignactivityactualcost: "totalcampaignactivityactualcost"
,transactioncurrencyid: "transactioncurrencyid"
,typecode: "typecode"
};

var Form_88de0f86_b850_4dad_9751_c2b8437f2625_Controls = {
actualend: "actualend"
,actualstart: "actualstart"
,budgetedcost: "budgetedcost"
,codename: "codename"
,createdon: "createdon"
,description: "description"
,expectedresponse: "expectedresponse"
,expectedrevenue: "expectedrevenue"
,modifiedby: "modifiedby"
,modifiedon: "modifiedon"
,name: "name"
,notescontrol: "notescontrol"
,objective: "objective"
,othercost: "othercost"
,ownerid: "ownerid"
,pricelistid: "pricelistid"
,proposedend: "proposedend"
,proposedstart: "proposedstart"
,statuscode: "statuscode"
,totalactualcost: "totalactualcost"
,totalcampaignactivityactualcost: "totalcampaignactivityactualcost"
,transactioncurrencyid: "transactioncurrencyid"
,typecode: "typecode"
};

