var EntityLogicalName = "campaignresponse";
var Form_c7a6dff6_b081_4b6a_b092_b33085cabc1d_Properties = {
channeltypecode: "channeltypecode"
,companyname: "companyname"
,customer: "customer"
,description: "description"
,emailaddress: "emailaddress"
,fax: "fax"
,firstname: "firstname"
,lastname: "lastname"
,originatingactivityid: "originatingactivityid"
,ownerid: "ownerid"
,partner: "partner"
,prioritycode: "prioritycode"
,promotioncodename: "promotioncodename"
,receivedon: "receivedon"
,regardingobjectid: "regardingobjectid"
,responsecode: "responsecode"
,scheduledend: "scheduledend"
,subject: "subject"
,telephone: "telephone"
};

var Form_c7a6dff6_b081_4b6a_b092_b33085cabc1d_Controls = {
channeltypecode: "channeltypecode"
,companyname: "companyname"
,customer: "customer"
,description: "description"
,emailaddress: "emailaddress"
,fax: "fax"
,firstname: "firstname"
,lastname: "lastname"
,notescontrol: "notescontrol"
,originatingactivityid: "originatingactivityid"
,ownerid: "ownerid"
,partner: "partner"
,prioritycode: "prioritycode"
,promotioncodename: "promotioncodename"
,receivedon: "receivedon"
,regardingobjectid: "regardingobjectid"
,responsecode: "responsecode"
,scheduledend: "scheduledend"
,subject: "subject"
,telephone: "telephone"
};

