var EntityLogicalName = "campaignresponse";
var Form_db9d45a2_5190_4373_af67_d729d51d173f_Properties = {
channeltypecode: "channeltypecode"
,companyname: "companyname"
,customer: "customer"
,description: "description"
,emailaddress: "emailaddress"
,firstname: "firstname"
,lastname: "lastname"
,ownerid: "ownerid"
,partner: "partner"
,prioritycode: "prioritycode"
,promotioncodename: "promotioncodename"
,receivedon: "receivedon"
,regardingobjectid: "regardingobjectid"
,responsecode: "responsecode"
,scheduledend: "scheduledend"
,statecode: "statecode"
,subject: "subject"
,telephone: "telephone"
};

var Form_db9d45a2_5190_4373_af67_d729d51d173f_Controls = {
channeltypecode: "channeltypecode"
,companyname: "companyname"
,customer: "customer"
,description: "description"
,emailaddress: "emailaddress"
,firstname: "firstname"
,header_ownerid: "header_ownerid"
,header_regardingobjectid: "header_regardingobjectid"
,header_responsecode: "header_responsecode"
,header_statecode: "header_statecode"
,lastname: "lastname"
,ownerid: "ownerid"
,partner: "partner"
,prioritycode: "prioritycode"
,promotioncodename: "promotioncodename"
,receivedon: "receivedon"
,regardingobjectid: "regardingobjectid"
,responsecode: "responsecode"
,scheduledend: "scheduledend"
,subject: "subject"
,telephone: "telephone"
};

