var EntityLogicalName = "incident";
var Form_f658c846_f74c_459b_b591_b97558958106_Properties = {
caseorigincode: "caseorigincode"
,casetypecode: "casetypecode"
,contractdetailid: "contractdetailid"
,contractid: "contractid"
,contractservicelevelcode: "contractservicelevelcode"
,customerid: "customerid"
,customersatisfactioncode: "customersatisfactioncode"
,followupby: "followupby"
,kbarticleid: "kbarticleid"
,ownerid: "ownerid"
,prioritycode: "prioritycode"
,productid: "productid"
,productserialnumber: "productserialnumber"
,statuscode: "statuscode"
,subjectid: "subjectid"
,title: "title"
};

var Form_f658c846_f74c_459b_b591_b97558958106_Controls = {
caseorigincode: "caseorigincode"
,casetypecode: "casetypecode"
,contractdetailid: "contractdetailid"
,contractid: "contractid"
,contractservicelevelcode: "contractservicelevelcode"
,customerid: "customerid"
,customersatisfactioncode: "customersatisfactioncode"
,followupby: "followupby"
,kbarticleid: "kbarticleid"
,kbviewer: "kbviewer"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,prioritycode: "prioritycode"
,productid: "productid"
,productserialnumber: "productserialnumber"
,statuscode: "statuscode"
,subjectid: "subjectid"
,title: "title"
,WebResource_RecordWall: "WebResource_RecordWall"
};

