var EntityLogicalName = "competitor";
var Form_b81139b0_9849_4def_836b_75c4a0f0b03a_Properties = {
address1_city: "address1_city"
,address1_country: "address1_country"
,address1_line1: "address1_line1"
,address1_line2: "address1_line2"
,address1_line3: "address1_line3"
,address1_postalcode: "address1_postalcode"
,address1_stateorprovince: "address1_stateorprovince"
,keyproduct: "keyproduct"
,name: "name"
,opportunities: "opportunities"
,overview: "overview"
,reportedrevenue: "reportedrevenue"
,stockexchange: "stockexchange"
,strengths: "strengths"
,threats: "threats"
,transactioncurrencyid: "transactioncurrencyid"
,weaknesses: "weaknesses"
,websiteurl: "websiteurl"
};

var Form_b81139b0_9849_4def_836b_75c4a0f0b03a_Controls = {
address1_city: "address1_city"
,address1_country: "address1_country"
,address1_line1: "address1_line1"
,address1_line2: "address1_line2"
,address1_line3: "address1_line3"
,address1_postalcode: "address1_postalcode"
,address1_stateorprovince: "address1_stateorprovince"
,keyproduct: "keyproduct"
,name: "name"
,notescontrol: "notescontrol"
,opportunities: "opportunities"
,overview: "overview"
,reportedrevenue: "reportedrevenue"
,stockexchange: "stockexchange"
,strengths: "strengths"
,threats: "threats"
,transactioncurrencyid: "transactioncurrencyid"
,weaknesses: "weaknesses"
,WebResource_RecordWall: "WebResource_RecordWall"
,websiteurl: "websiteurl"
};

