var EntityLogicalName = "contract";
var Form_9198bc43_88a8_40c0_bd25_6be0a13ee30f_Properties = {
activeon: "activeon"
,billingcustomerid: "billingcustomerid"
,billingendon: "billingendon"
,billingfrequencycode: "billingfrequencycode"
,billingstarton: "billingstarton"
,billtoaddress: "billtoaddress"
,cancelon: "cancelon"
,contractlanguage: "contractlanguage"
,contractnumber: "contractnumber"
,contractservicelevelcode: "contractservicelevelcode"
,contracttemplateid: "contracttemplateid"
,createdon: "createdon"
,customerid: "customerid"
,duration: "duration"
,expireson: "expireson"
,netprice: "netprice"
,originatingcontract: "originatingcontract"
,ownerid: "ownerid"
,serviceaddress: "serviceaddress"
,statuscode: "statuscode"
,title: "title"
,totaldiscount: "totaldiscount"
,totalprice: "totalprice"
,transactioncurrencyid: "transactioncurrencyid"
,usediscountaspercentage: "usediscountaspercentage"
};

var Form_9198bc43_88a8_40c0_bd25_6be0a13ee30f_Controls = {
activeon: "activeon"
,billingcustomerid: "billingcustomerid"
,billingendon: "billingendon"
,billingfrequencycode: "billingfrequencycode"
,billingstarton: "billingstarton"
,billtoaddress: "billtoaddress"
,cancelon: "cancelon"
,Contract_lines: "Contract_lines"
,contractlanguage: "contractlanguage"
,contractnumber: "contractnumber"
,contractservicelevelcode: "contractservicelevelcode"
,contracttemplateid: "contracttemplateid"
,customerid: "customerid"
,duration: "duration"
,expireson: "expireson"
,header_createdon: "header_createdon"
,header_ownerid: "header_ownerid"
,header_status: "header_status"
,netprice: "netprice"
,notescontrol: "notescontrol"
,originatingcontract: "originatingcontract"
,ownerid: "ownerid"
,serviceaddress: "serviceaddress"
,title: "title"
,totaldiscount: "totaldiscount"
,totalprice: "totalprice"
,transactioncurrencyid: "transactioncurrencyid"
,usediscountaspercentage: "usediscountaspercentage"
};

