var EntityLogicalName = "contract";
var Form_2ec5c846_77a9_4e14_bf66_f1f247a8cf7a_Properties = {
activeon: "activeon"
,billingcustomerid: "billingcustomerid"
,billingendon: "billingendon"
,billingfrequencycode: "billingfrequencycode"
,billingstarton: "billingstarton"
,billtoaddress: "billtoaddress"
,cancelon: "cancelon"
,contractlanguage: "contractlanguage"
,contractnumber: "contractnumber"
,contractservicelevelcode: "contractservicelevelcode"
,contracttemplateid: "contracttemplateid"
,customerid: "customerid"
,duration: "duration"
,expireson: "expireson"
,netprice: "netprice"
,originatingcontract: "originatingcontract"
,ownerid: "ownerid"
,serviceaddress: "serviceaddress"
,title: "title"
,totaldiscount: "totaldiscount"
,totalprice: "totalprice"
,transactioncurrencyid: "transactioncurrencyid"
,usediscountaspercentage: "usediscountaspercentage"
};

var Form_2ec5c846_77a9_4e14_bf66_f1f247a8cf7a_Controls = {
activeon: "activeon"
,billingcustomerid: "billingcustomerid"
,billingendon: "billingendon"
,billingfrequencycode: "billingfrequencycode"
,billingstarton: "billingstarton"
,billtoaddress: "billtoaddress"
,cancelon: "cancelon"
,contractlanguage: "contractlanguage"
,contractnumber: "contractnumber"
,contractservicelevelcode: "contractservicelevelcode"
,contracttemplateid: "contracttemplateid"
,customerid: "customerid"
,duration: "duration"
,expireson: "expireson"
,netprice: "netprice"
,notescontrol: "notescontrol"
,originatingcontract: "originatingcontract"
,ownerid: "ownerid"
,serviceaddress: "serviceaddress"
,title: "title"
,totaldiscount: "totaldiscount"
,totalprice: "totalprice"
,transactioncurrencyid: "transactioncurrencyid"
,usediscountaspercentage: "usediscountaspercentage"
};

