var EntityLogicalName = "contact";
var Form_1fed44d1_ae68_4a41_bd2b_f13acac4acfa_Properties = {
address1_composite: "address1_composite"
,address1_freighttermscode: "address1_freighttermscode"
,address1_latitude: "address1_latitude"
,address1_longitude: "address1_longitude"
,address1_shippingmethodcode: "address1_shippingmethodcode"
,anniversary: "anniversary"
,birthdate: "birthdate"
,creditlimit: "creditlimit"
,creditonhold: "creditonhold"
,description: "description"
,donotbulkemail: "donotbulkemail"
,donotemail: "donotemail"
,donotfax: "donotfax"
,donotphone: "donotphone"
,donotpostalmail: "donotpostalmail"
,donotsendmm: "donotsendmm"
,emailaddress1: "emailaddress1"
,familystatuscode: "familystatuscode"
,fullname: "fullname"
,int_facebook: "int_facebook"
,int_kloutscore: "int_kloutscore"
,int_twitter: "int_twitter"
,jobtitle: "jobtitle"
,lastusedincampaign: "lastusedincampaign"
,mobilephone: "mobilephone"
,originatingleadid: "originatingleadid"
,ownerid: "ownerid"
,parentcustomerid: "parentcustomerid"
,paymenttermscode: "paymenttermscode"
,preferredcontactmethodcode: "preferredcontactmethodcode"
,spousesname: "spousesname"
,telephone1: "telephone1"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_1fed44d1_ae68_4a41_bd2b_f13acac4acfa_Controls = {
address1_composite: "address1_composite"
,address1_freighttermscode: "address1_freighttermscode"
,address1_latitude: "address1_latitude"
,address1_longitude: "address1_longitude"
,address1_shippingmethodcode: "address1_shippingmethodcode"
,anniversary: "anniversary"
,birthdate: "birthdate"
,contactcasessgrid: "contactcasessgrid"
,contactopportunitiesgrid: "contactopportunitiesgrid"
,contactquickform: "contactquickform"
,creditlimit: "creditlimit"
,creditonhold: "creditonhold"
,description: "description"
,donotbulkemail: "donotbulkemail"
,donotemail: "donotemail"
,donotfax: "donotfax"
,donotphone: "donotphone"
,donotpostalmail: "donotpostalmail"
,donotsendmm: "donotsendmm"
,emailaddress1: "emailaddress1"
,familystatuscode: "familystatuscode"
,fullname: "fullname"
,header_ownerid: "header_ownerid"
,int_facebook: "int_facebook"
,int_kloutscore: "int_kloutscore"
,int_twitter: "int_twitter"
,jobtitle: "jobtitle"
,lastusedincampaign: "lastusedincampaign"
,mapcontrol: "mapcontrol"
,mobilephone: "mobilephone"
,notescontrol: "notescontrol"
,originatingleadid: "originatingleadid"
,parentcustomerid: "parentcustomerid"
,paymenttermscode: "paymenttermscode"
,preferredcontactmethodcode: "preferredcontactmethodcode"
,spousesname: "spousesname"
,telephone1: "telephone1"
,transactioncurrencyid: "transactioncurrencyid"
};

