var EntityLogicalName = "emailserverprofile";
var Form_d7735d4f_13c2_4f0e_a4ff_09e7510d84ed_Properties = {
description: "description"
,emailservertypename: "emailservertypename"
,exchangeonlinetenantid: "exchangeonlinetenantid"
,incomingauthenticationprotocol: "incomingauthenticationprotocol"
,incomingcredentialretrieval: "incomingcredentialretrieval"
,incomingpassword: "incomingpassword"
,incomingportnumber: "incomingportnumber"
,incomingserverlocation: "incomingserverlocation"
,incominguseimpersonation: "incominguseimpersonation"
,incomingusername: "incomingusername"
,incomingusessl: "incomingusessl"
,maxconcurrentconnections: "maxconcurrentconnections"
,minpollingintervalinminutes: "minpollingintervalinminutes"
,moveundeliveredemails: "moveundeliveredemails"
,name: "name"
,outgoingauthenticationprotocol: "outgoingauthenticationprotocol"
,outgoingcredentialretrieval: "outgoingcredentialretrieval"
,outgoingpassword: "outgoingpassword"
,outgoingportnumber: "outgoingportnumber"
,outgoingserverlocation: "outgoingserverlocation"
,outgoinguseimpersonation: "outgoinguseimpersonation"
,outgoingusername: "outgoingusername"
,outgoingusessl: "outgoingusessl"
,ownerid: "ownerid"
,processemailsreceivedafter: "processemailsreceivedafter"
,sendemailalert: "sendemailalert"
,servertype: "servertype"
,statecode: "statecode"
,timeoutmailboxconnection: "timeoutmailboxconnection"
,timeoutmailboxconnectionafteramount: "timeoutmailboxconnectionafteramount"
,useautodiscover: "useautodiscover"
,usedefaulttenantid: "usedefaulttenantid"
,usesamesettingsforoutgoingconnections: "usesamesettingsforoutgoingconnections"
};

var Form_d7735d4f_13c2_4f0e_a4ff_09e7510d84ed_Controls = {
description: "description"
,emailservertypename: "emailservertypename"
,exchangeonlinetenantid: "exchangeonlinetenantid"
,footer_statecode: "footer_statecode"
,incomingauthenticationprotocol: "incomingauthenticationprotocol"
,incomingcredentialretrieval: "incomingcredentialretrieval"
,incomingpassword: "incomingpassword"
,incomingportnumber: "incomingportnumber"
,incomingserverlocation: "incomingserverlocation"
,incominguseimpersonation: "incominguseimpersonation"
,incomingusername: "incomingusername"
,incomingusessl: "incomingusessl"
,maxconcurrentconnections: "maxconcurrentconnections"
,minpollingintervalinminutes: "minpollingintervalinminutes"
,moveundeliveredemails: "moveundeliveredemails"
,name: "name"
,notescontrol: "notescontrol"
,outgoingauthenticationprotocol: "outgoingauthenticationprotocol"
,outgoingcredentialretrieval: "outgoingcredentialretrieval"
,outgoingpassword: "outgoingpassword"
,outgoingportnumber: "outgoingportnumber"
,outgoingserverlocation: "outgoingserverlocation"
,outgoinguseimpersonation: "outgoinguseimpersonation"
,outgoingusername: "outgoingusername"
,outgoingusessl: "outgoingusessl"
,ownerid: "ownerid"
,processemailsreceivedafter: "processemailsreceivedafter"
,sendemailalert: "sendemailalert"
,servertype: "servertype"
,timeoutmailboxconnection: "timeoutmailboxconnection"
,timeoutmailboxconnectionafteramount: "timeoutmailboxconnectionafteramount"
,useautodiscover: "useautodiscover"
,usedefaulttenantid: "usedefaulttenantid"
,usesamesettingsforoutgoingconnections: "usesamesettingsforoutgoingconnections"
};

