var EntityLogicalName = "msdyn_inventoryjournal";
var Form_63b1734b_2a54_44b5_a912_6e8609721ba6_Properties = {
msdyn_allocatedtoworkorder: "msdyn_allocatedtoworkorder"
,msdyn_inventoryadjustmentproduct: "msdyn_inventoryadjustmentproduct"
,msdyn_journaltype: "msdyn_journaltype"
,msdyn_name: "msdyn_name"
,msdyn_originatingjournal: "msdyn_originatingjournal"
,msdyn_product: "msdyn_product"
,msdyn_purchaseorderproduct: "msdyn_purchaseorderproduct"
,msdyn_purchaseorderreceiptproduct: "msdyn_purchaseorderreceiptproduct"
,msdyn_quantity: "msdyn_quantity"
,msdyn_reversal: "msdyn_reversal"
,msdyn_rmareceiptproduct: "msdyn_rmareceiptproduct"
,msdyn_transactiontype: "msdyn_transactiontype"
,msdyn_unit: "msdyn_unit"
,msdyn_warehouse: "msdyn_warehouse"
,msdyn_workorderproduct: "msdyn_workorderproduct"
,ownerid: "ownerid"
,statecode: "statecode"
};

var Form_63b1734b_2a54_44b5_a912_6e8609721ba6_Controls = {
footer_statecode: "footer_statecode"
,msdyn_allocatedtoworkorder: "msdyn_allocatedtoworkorder"
,msdyn_inventoryadjustmentproduct: "msdyn_inventoryadjustmentproduct"
,msdyn_journaltype: "msdyn_journaltype"
,msdyn_name: "msdyn_name"
,msdyn_originatingjournal: "msdyn_originatingjournal"
,msdyn_product: "msdyn_product"
,msdyn_purchaseorderproduct: "msdyn_purchaseorderproduct"
,msdyn_purchaseorderreceiptproduct: "msdyn_purchaseorderreceiptproduct"
,msdyn_quantity: "msdyn_quantity"
,msdyn_reversal: "msdyn_reversal"
,msdyn_rmareceiptproduct: "msdyn_rmareceiptproduct"
,msdyn_transactiontype: "msdyn_transactiontype"
,msdyn_unit: "msdyn_unit"
,msdyn_warehouse: "msdyn_warehouse"
,msdyn_workorderproduct: "msdyn_workorderproduct"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
};

