var EntityLogicalName = "invoice";
var Form_e42e464f_c249_4005_896e_cdee472d7e1e_Properties = {
billto_composite: "billto_composite"
,createdon: "createdon"
,customerid: "customerid"
,datedelivered: "datedelivered"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,duedate: "duedate"
,freightamount: "freightamount"
,invoicenumber: "invoicenumber"
,ispricelocked: "ispricelocked"
,msdyn_invoicedate: "msdyn_invoicedate"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,opportunityid: "opportunityid"
,ownerid: "ownerid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,salesorderid: "salesorderid"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

var Form_e42e464f_c249_4005_896e_cdee472d7e1e_Controls = {
billto_composite: "billto_composite"
,createdon: "createdon"
,customerid: "customerid"
,datedelivered: "datedelivered"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,duedate: "duedate"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,freightamount: "freightamount"
,GridInvoicingPeriod: "GridInvoicingPeriod"
,GridServiceLines: "GridServiceLines"
,header_ownerid: "header_ownerid"
,header_statecode: "header_statecode"
,header_statuscode: "header_statuscode"
,header_totalamount: "header_totalamount"
,invoicedetailsGrid: "invoicedetailsGrid"
,invoicenumber: "invoicenumber"
,ispricelocked: "ispricelocked"
,msdyn_invoicedate: "msdyn_invoicedate"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,notescontrol: "notescontrol"
,opportunityid: "opportunityid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,ProductSuggestions_LinkControl: "ProductSuggestions_LinkControl"
,salesorderid: "salesorderid"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

