var EntityLogicalName = "msdyn_invoicelinetransaction";
var Form_9a927ec1_acfe_4d85_a637_d7acd67f04ba_Properties = {
msdyn_accountcustomer: "msdyn_accountcustomer"
,msdyn_amount: "msdyn_amount"
,msdyn_amountmethod: "msdyn_amountmethod"
,msdyn_basisquantity: "msdyn_basisquantity"
,msdyn_billingtype: "msdyn_billingtype"
,msdyn_bookableresource: "msdyn_bookableresource"
,msdyn_contactcustomer: "msdyn_contactcustomer"
,msdyn_correction: "msdyn_correction"
,msdyn_customertype: "msdyn_customertype"
,msdyn_description: "msdyn_description"
,msdyn_documentdate: "msdyn_documentdate"
,msdyn_enddatetime: "msdyn_enddatetime"
,msdyn_externaldescription: "msdyn_externaldescription"
,msdyn_invoiceline: "msdyn_invoiceline"
,msdyn_originalinvoicelinedetail: "msdyn_originalinvoicelinedetail"
,msdyn_price: "msdyn_price"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_project: "msdyn_project"
,msdyn_quantity: "msdyn_quantity"
,msdyn_resourcecategory: "msdyn_resourcecategory"
,msdyn_resourceorganizationalunitid: "msdyn_resourceorganizationalunitid"
,msdyn_salescontractline: "msdyn_salescontractline"
,msdyn_startdatetime: "msdyn_startdatetime"
,msdyn_task: "msdyn_task"
,msdyn_transactioncategory: "msdyn_transactioncategory"
,msdyn_transactionclassification: "msdyn_transactionclassification"
,msdyn_transactiontypecode: "msdyn_transactiontypecode"
,msdyn_unit: "msdyn_unit"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_9a927ec1_acfe_4d85_a637_d7acd67f04ba_Controls = {
CorrectionQuickView: "CorrectionQuickView"
,msdyn_accountcustomer: "msdyn_accountcustomer"
,msdyn_amount: "msdyn_amount"
,msdyn_amountmethod: "msdyn_amountmethod"
,msdyn_basisquantity: "msdyn_basisquantity"
,msdyn_billingtype: "msdyn_billingtype"
,msdyn_bookableresource: "msdyn_bookableresource"
,msdyn_contactcustomer: "msdyn_contactcustomer"
,msdyn_correction: "msdyn_correction"
,msdyn_customertype: "msdyn_customertype"
,msdyn_description: "msdyn_description"
,msdyn_documentdate: "msdyn_documentdate"
,msdyn_enddatetime: "msdyn_enddatetime"
,msdyn_externaldescription: "msdyn_externaldescription"
,msdyn_invoiceline: "msdyn_invoiceline"
,msdyn_originalinvoicelinedetail: "msdyn_originalinvoicelinedetail"
,msdyn_price: "msdyn_price"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_project: "msdyn_project"
,msdyn_quantity: "msdyn_quantity"
,msdyn_resourcecategory: "msdyn_resourcecategory"
,msdyn_resourceorganizationalunitid: "msdyn_resourceorganizationalunitid"
,msdyn_salescontractline: "msdyn_salescontractline"
,msdyn_startdatetime: "msdyn_startdatetime"
,msdyn_task: "msdyn_task"
,msdyn_transactioncategory: "msdyn_transactioncategory"
,msdyn_transactionclassification: "msdyn_transactionclassification"
,msdyn_transactiontypecode: "msdyn_transactiontypecode"
,msdyn_unit: "msdyn_unit"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

