var EntityLogicalName = "invoice";
var Form_a0445736_61ca_495d_8e03_855be3a56eff_Properties = {
billto_composite: "billto_composite"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,duedate: "duedate"
,freightamount: "freightamount"
,invoicenumber: "invoicenumber"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_projectinvoicestatus: "msdyn_projectinvoicestatus"
,name: "name"
,opportunityid: "opportunityid"
,ownerid: "ownerid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,salesorderid: "salesorderid"
,statecode: "statecode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

var Form_a0445736_61ca_495d_8e03_855be3a56eff_Controls = {
billto_composite: "billto_composite"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,duedate: "duedate"
,freightamount: "freightamount"
,header_msdyn_projectinvoicestatus: "header_msdyn_projectinvoicestatus"
,header_ownerid: "header_ownerid"
,header_statecode: "header_statecode"
,header_totalamount: "header_totalamount"
,invoicedetailsGrid: "invoicedetailsGrid"
,invoicenumber: "invoicenumber"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,notescontrol: "notescontrol"
,opportunityid: "opportunityid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,ProjectInvoiceLines: "ProjectInvoiceLines"
,salesorderid: "salesorderid"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

