var EntityLogicalName = "msdyn_journalline";
var Form_d185f46c_1652_42bc_8509_7a7b6ce58cb5_Properties = {
msdyn_accountcustomer: "msdyn_accountcustomer"
,msdyn_accountvendor: "msdyn_accountvendor"
,msdyn_amount: "msdyn_amount"
,msdyn_amountmethod: "msdyn_amountmethod"
,msdyn_basisamount: "msdyn_basisamount"
,msdyn_basisquantity: "msdyn_basisquantity"
,msdyn_billingtype: "msdyn_billingtype"
,msdyn_bookableresource: "msdyn_bookableresource"
,msdyn_contactcustomer: "msdyn_contactcustomer"
,msdyn_contactvendor: "msdyn_contactvendor"
,msdyn_customertype: "msdyn_customertype"
,msdyn_description: "msdyn_description"
,msdyn_documentdate: "msdyn_documentdate"
,msdyn_enddatetime: "msdyn_enddatetime"
,msdyn_externaldescription: "msdyn_externaldescription"
,msdyn_percent: "msdyn_percent"
,msdyn_price: "msdyn_price"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_product: "msdyn_product"
,msdyn_project: "msdyn_project"
,msdyn_quantity: "msdyn_quantity"
,msdyn_resourcecategory: "msdyn_resourcecategory"
,msdyn_startdatetime: "msdyn_startdatetime"
,msdyn_task: "msdyn_task"
,msdyn_transactioncategory: "msdyn_transactioncategory"
,msdyn_transactionclassification: "msdyn_transactionclassification"
,msdyn_transactiontypecode: "msdyn_transactiontypecode"
,msdyn_unit: "msdyn_unit"
,msdyn_unitschedule: "msdyn_unitschedule"
,msdyn_vendortype: "msdyn_vendortype"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_d185f46c_1652_42bc_8509_7a7b6ce58cb5_Controls = {
msdyn_accountcustomer: "msdyn_accountcustomer"
,msdyn_accountvendor: "msdyn_accountvendor"
,msdyn_amount: "msdyn_amount"
,msdyn_amountmethod: "msdyn_amountmethod"
,msdyn_basisamount: "msdyn_basisamount"
,msdyn_basisquantity: "msdyn_basisquantity"
,msdyn_billingtype: "msdyn_billingtype"
,msdyn_bookableresource: "msdyn_bookableresource"
,msdyn_contactcustomer: "msdyn_contactcustomer"
,msdyn_contactvendor: "msdyn_contactvendor"
,msdyn_customertype: "msdyn_customertype"
,msdyn_description: "msdyn_description"
,msdyn_documentdate: "msdyn_documentdate"
,msdyn_enddatetime: "msdyn_enddatetime"
,msdyn_externaldescription: "msdyn_externaldescription"
,msdyn_percent: "msdyn_percent"
,msdyn_price: "msdyn_price"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_product: "msdyn_product"
,msdyn_project: "msdyn_project"
,msdyn_quantity: "msdyn_quantity"
,msdyn_resourcecategory: "msdyn_resourcecategory"
,msdyn_startdatetime: "msdyn_startdatetime"
,msdyn_task: "msdyn_task"
,msdyn_transactioncategory: "msdyn_transactioncategory"
,msdyn_transactionclassification: "msdyn_transactionclassification"
,msdyn_transactiontypecode: "msdyn_transactiontypecode"
,msdyn_unit: "msdyn_unit"
,msdyn_unitschedule: "msdyn_unitschedule"
,msdyn_vendortype: "msdyn_vendortype"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

