var EntityLogicalName = "knowledgearticle";
var Form_e7ef555e_7f57_4164_b604_59fa4f0a7e2e_Properties = {
articlepublicnumber: "articlepublicnumber"
,content: "content"
,createdby: "createdby"
,createdon: "createdon"
,description: "description"
,expirationdate: "expirationdate"
,isinternal: "isinternal"
,keywords: "keywords"
,languagelocaleid: "languagelocaleid"
,majorversionnumber: "majorversionnumber"
,minorversionnumber: "minorversionnumber"
,modifiedby: "modifiedby"
,modifiedon: "modifiedon"
,ownerid: "ownerid"
,parentarticlecontentid: "parentarticlecontentid"
,primaryauthorid: "primaryauthorid"
,publishon: "publishon"
,rating: "rating"
,rootarticleid: "rootarticleid"
,statuscode: "statuscode"
,subjectid: "subjectid"
,title: "title"
};

var Form_e7ef555e_7f57_4164_b604_59fa4f0a7e2e_Controls = {
articlepublicnumber: "articlepublicnumber"
,articleviewcountquickform: "articleviewcountquickform"
,content: "content"
,creadedon: "creadedon"
,createdname: "createdname"
,description: "description"
,expirationdate: "expirationdate"
,Feedback: "Feedback"
,header_languagelocaleid: "header_languagelocaleid"
,header_majorversionnumber: "header_majorversionnumber"
,header_minorversionnumber: "header_minorversionnumber"
,header_statuscode: "header_statuscode"
,IFRAME_articlecontent: "IFRAME_articlecontent"
,isinternal: "isinternal"
,keywords: "keywords"
,KnowledgearticleviewsGrid: "KnowledgearticleviewsGrid"
,languagelocaleid: "languagelocaleid"
,modifiedname: "modifiedname"
,modifiedon: "modifiedon"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,primaryauthorid: "primaryauthorid"
,publishon: "publishon"
,rating: "rating"
,relatedarticlequickform: "relatedarticlequickform"
,RelatedCasesGrid: "RelatedCasesGrid"
,RelatedCategoriesGrid: "RelatedCategoriesGrid"
,relatedproducts: "relatedproducts"
,RelatedTranslationsGrid: "RelatedTranslationsGrid"
,relatedversionsquickform: "relatedversionsquickform"
,statuscode: "statuscode"
,subjectid: "subjectid"
,title: "title"
};

