var EntityLogicalName = "lead";
var Form_e3b6ddb7_8df0_4410_ac7b_fd32e5053d38_Properties = {
address1_composite: "address1_composite"
,campaignid: "campaignid"
,companyname: "companyname"
,description: "description"
,donotbulkemail: "donotbulkemail"
,donotemail: "donotemail"
,donotphone: "donotphone"
,donotpostalmail: "donotpostalmail"
,donotsendmm: "donotsendmm"
,emailaddress1: "emailaddress1"
,fullname: "fullname"
,industrycode: "industrycode"
,jobtitle: "jobtitle"
,lastusedincampaign: "lastusedincampaign"
,leadqualitycode: "leadqualitycode"
,leadsourcecode: "leadsourcecode"
,mobilephone: "mobilephone"
,msdyn_ordertype: "msdyn_ordertype"
,numberofemployees: "numberofemployees"
,ownerid: "ownerid"
,preferredcontactmethodcode: "preferredcontactmethodcode"
,revenue: "revenue"
,sic: "sic"
,statuscode: "statuscode"
,subject: "subject"
,telephone1: "telephone1"
,transactioncurrencyid: "transactioncurrencyid"
,websiteurl: "websiteurl"
};

var Form_e3b6ddb7_8df0_4410_ac7b_fd32e5053d38_Controls = {
address1_composite: "address1_composite"
,campaignid: "campaignid"
,companyname: "companyname"
,Competitors: "Competitors"
,description: "description"
,donotbulkemail: "donotbulkemail"
,donotemail: "donotemail"
,donotphone: "donotphone"
,donotpostalmail: "donotpostalmail"
,donotsendmm: "donotsendmm"
,emailaddress1: "emailaddress1"
,fullname: "fullname"
,header_leadqualitycode: "header_leadqualitycode"
,header_leadsourcecode: "header_leadsourcecode"
,header_ownerid: "header_ownerid"
,header_statuscode: "header_statuscode"
,industrycode: "industrycode"
,jobtitle: "jobtitle"
,lastusedincampaign: "lastusedincampaign"
,mapcontrol: "mapcontrol"
,mobilephone: "mobilephone"
,msdyn_ordertype: "msdyn_ordertype"
,notescontrol: "notescontrol"
,numberofemployees: "numberofemployees"
,preferredcontactmethodcode: "preferredcontactmethodcode"
,revenue: "revenue"
,sic: "sic"
,Stakeholders: "Stakeholders"
,subject: "subject"
,telephone1: "telephone1"
,transactioncurrencyid: "transactioncurrencyid"
,websiteurl: "websiteurl"
};

