var EntityLogicalName = "mailbox";
var Form_d08328e6_d988_44df_8d76_d4e83674f85c_Properties = {
actdeliverymethod: "actdeliverymethod"
,actstatus: "actstatus"
,allowemailconnectortousecredentials: "allowemailconnectortousecredentials"
,emailaddress: "emailaddress"
,emailserverprofile: "emailserverprofile"
,incomingemaildeliverymethod: "incomingemaildeliverymethod"
,incomingemailstatus: "incomingemailstatus"
,isemailaddressapprovedbyo365admin: "isemailaddressapprovedbyo365admin"
,isforwardmailbox: "isforwardmailbox"
,name: "name"
,outgoingemaildeliverymethod: "outgoingemaildeliverymethod"
,outgoingemailstatus: "outgoingemailstatus"
,ownerid: "ownerid"
,password: "password"
,processanddeleteemails: "processanddeleteemails"
,regardingobjectid: "regardingobjectid"
,statecode: "statecode"
,testmailboxaccesscompletedon: "testmailboxaccesscompletedon"
,username: "username"
};

var Form_d08328e6_d988_44df_8d76_d4e83674f85c_Controls = {
actdeliverymethod: "actdeliverymethod"
,actstatus: "actstatus"
,allowemailconnectortousecredentials: "allowemailconnectortousecredentials"
,emailaddress: "emailaddress"
,emailserverprofile: "emailserverprofile"
,footer_statecode: "footer_statecode"
,incomingemaildeliverymethod: "incomingemaildeliverymethod"
,incomingemailstatus: "incomingemailstatus"
,isemailaddressapprovedbyo365admin: "isemailaddressapprovedbyo365admin"
,isforwardmailbox: "isforwardmailbox"
,name: "name"
,notescontrol: "notescontrol"
,outgoingemaildeliverymethod: "outgoingemaildeliverymethod"
,outgoingemailstatus: "outgoingemailstatus"
,ownerid: "ownerid"
,password: "password"
,processanddeleteemails: "processanddeleteemails"
,regardingobjectid: "regardingobjectid"
,testmailboxaccesscompletedon: "testmailboxaccesscompletedon"
,username: "username"
};

