var EntityLogicalName = "opportunityproduct";
var Form_38a21ef8_da5d_4f00_9779_fae8cd94a015_Properties = {
baseamount: "baseamount"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,msdyn_billingmethod: "msdyn_billingmethod"
,msdyn_budgetamount: "msdyn_budgetamount"
,msdyn_linetype: "msdyn_linetype"
,opportunityid: "opportunityid"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,producttypecode: "producttypecode"
,quantity: "quantity"
,tax: "tax"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
};

var Form_38a21ef8_da5d_4f00_9779_fae8cd94a015_Controls = {
baseamount: "baseamount"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,msdyn_billingmethod: "msdyn_billingmethod"
,msdyn_budgetamount: "msdyn_budgetamount"
,msdyn_linetype: "msdyn_linetype"
,opportunityid: "opportunityid"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,producttypecode: "producttypecode"
,quantity: "quantity"
,tax: "tax"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
};

