var EntityLogicalName = "msdyn_opportunitylinetransaction";
var Form_49f3f79b_9dda_49a5_92d5_df6d8513f90d_Properties = {
msdyn_accountcustomer: "msdyn_accountcustomer"
,msdyn_accountvendor: "msdyn_accountvendor"
,msdyn_amount: "msdyn_amount"
,msdyn_amountmethod: "msdyn_amountmethod"
,msdyn_basisamount: "msdyn_basisamount"
,msdyn_basisquantity: "msdyn_basisquantity"
,msdyn_billingtype: "msdyn_billingtype"
,msdyn_bookableresource: "msdyn_bookableresource"
,msdyn_contactcustomer: "msdyn_contactcustomer"
,msdyn_contactvendor: "msdyn_contactvendor"
,msdyn_customertype: "msdyn_customertype"
,msdyn_description: "msdyn_description"
,msdyn_documentdate: "msdyn_documentdate"
,msdyn_enddatetime: "msdyn_enddatetime"
,msdyn_percent: "msdyn_percent"
,msdyn_price: "msdyn_price"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_product: "msdyn_product"
,msdyn_project: "msdyn_project"
,msdyn_quantity: "msdyn_quantity"
,msdyn_resourcecategory: "msdyn_resourcecategory"
,msdyn_startdatetime: "msdyn_startdatetime"
,msdyn_task: "msdyn_task"
,msdyn_transactioncategory: "msdyn_transactioncategory"
,msdyn_transactionclassification: "msdyn_transactionclassification"
,msdyn_transactiontypecode: "msdyn_transactiontypecode"
,msdyn_unit: "msdyn_unit"
,msdyn_vendortype: "msdyn_vendortype"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_49f3f79b_9dda_49a5_92d5_df6d8513f90d_Controls = {
msdyn_accountcustomer: "msdyn_accountcustomer"
,msdyn_accountvendor: "msdyn_accountvendor"
,msdyn_amount: "msdyn_amount"
,msdyn_amountmethod: "msdyn_amountmethod"
,msdyn_basisamount: "msdyn_basisamount"
,msdyn_basisquantity: "msdyn_basisquantity"
,msdyn_billingtype: "msdyn_billingtype"
,msdyn_bookableresource: "msdyn_bookableresource"
,msdyn_contactcustomer: "msdyn_contactcustomer"
,msdyn_contactvendor: "msdyn_contactvendor"
,msdyn_customertype: "msdyn_customertype"
,msdyn_description: "msdyn_description"
,msdyn_documentdate: "msdyn_documentdate"
,msdyn_enddatetime: "msdyn_enddatetime"
,msdyn_percent: "msdyn_percent"
,msdyn_price: "msdyn_price"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_product: "msdyn_product"
,msdyn_project: "msdyn_project"
,msdyn_quantity: "msdyn_quantity"
,msdyn_resourcecategory: "msdyn_resourcecategory"
,msdyn_startdatetime: "msdyn_startdatetime"
,msdyn_task: "msdyn_task"
,msdyn_transactioncategory: "msdyn_transactioncategory"
,msdyn_transactionclassification: "msdyn_transactionclassification"
,msdyn_transactiontypecode: "msdyn_transactiontypecode"
,msdyn_unit: "msdyn_unit"
,msdyn_vendortype: "msdyn_vendortype"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

