var EntityLogicalName = "opportunityproduct";
var Form_6378f4aa_3c80_4761_bc91_71c76acaee7f_Properties = {
baseamount: "baseamount"
,createdon: "createdon"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,msdyn_duration: "msdyn_duration"
,msdyn_enddate: "msdyn_enddate"
,msdyn_linetype: "msdyn_linetype"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_startdate: "msdyn_startdate"
,opportunityid: "opportunityid"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,producttypecode: "producttypecode"
,quantity: "quantity"
,tax: "tax"
,transactioncurrencyid: "transactioncurrencyid"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
};

var Form_6378f4aa_3c80_4761_bc91_71c76acaee7f_Controls = {
baseamount: "baseamount"
,createdon: "createdon"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,msdyn_duration: "msdyn_duration"
,msdyn_enddate: "msdyn_enddate"
,msdyn_linetype: "msdyn_linetype"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_startdate: "msdyn_startdate"
,opportunityid: "opportunityid"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,producttypecode: "producttypecode"
,quantity: "quantity"
,tax: "tax"
,transactioncurrencyid: "transactioncurrencyid"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
};

