var EntityLogicalName = "opportunity";
var Form_a2a56263_ec37_4991_a3b0_e7b37a71d818_Properties = {
campaignid: "campaignid"
,closeprobability: "closeprobability"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,estimatedclosedate: "estimatedclosedate"
,estimatedvalue: "estimatedvalue"
,freightamount: "freightamount"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,name: "name"
,opportunityratingcode: "opportunityratingcode"
,originatingleadid: "originatingleadid"
,ownerid: "ownerid"
,pricelevelid: "pricelevelid"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_a2a56263_ec37_4991_a3b0_e7b37a71d818_Controls = {
campaignid: "campaignid"
,closeprobability: "closeprobability"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,estimatedclosedate: "estimatedclosedate"
,estimatedvalue: "estimatedvalue"
,freightamount: "freightamount"
,header_customerid: "header_customerid"
,header_estimatedclosedate: "header_estimatedclosedate"
,header_estimatedvalue: "header_estimatedvalue"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,name: "name"
,notescontrol: "notescontrol"
,opportunityactivitiesgrid: "opportunityactivitiesgrid"
,opportunityproductsGrid: "opportunityproductsGrid"
,opportunityQuotesGrid: "opportunityQuotesGrid"
,opportunityratingcode: "opportunityratingcode"
,originatingleadid: "originatingleadid"
,ownerid: "ownerid"
,pricelevelid: "pricelevelid"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,WebResource_RecordWall: "WebResource_RecordWall"
};

