var EntityLogicalName = "opportunity";
var Form_a837e4a7_01b8_4f82_a475_be9abd67e667_Properties = {
closeprobability: "closeprobability"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,estimatedclosedate: "estimatedclosedate"
,estimatedvalue: "estimatedvalue"
,freightamount: "freightamount"
,int_addtoforecast: "int_addtoforecast"
,int_discountapproved: "int_discountapproved"
,int_forecast: "int_forecast"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_workordertype: "msdyn_workordertype"
,name: "name"
,ownerid: "ownerid"
,parentaccountid: "parentaccountid"
,parentcontactid: "parentcontactid"
,pricelevelid: "pricelevelid"
,proposedsolution: "proposedsolution"
,salesstage: "salesstage"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_a837e4a7_01b8_4f82_a475_be9abd67e667_Controls = {
closeprobability: "closeprobability"
,competitors: "competitors"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,freightamount: "freightamount"
,header_closeprobability: "header_closeprobability"
,header_estimatedclosedate: "header_estimatedclosedate"
,header_estimatedvalue: "header_estimatedvalue"
,header_ownerid: "header_ownerid"
,int_addtoforecast: "int_addtoforecast"
,int_discountapproved: "int_discountapproved"
,int_forecast: "int_forecast"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_workordertype: "msdyn_workordertype"
,name: "name"
,notescontrol: "notescontrol"
,OpportunityContact: "OpportunityContact"
,opportunityproductsGrid: "opportunityproductsGrid"
,parentaccountid: "parentaccountid"
,pricelevelid: "pricelevelid"
,ProductSuggestions_LinkControl: "ProductSuggestions_LinkControl"
,proposedsolution: "proposedsolution"
,Pursuit_Team: "Pursuit_Team"
,quote: "quote"
,salesstage: "salesstage"
,Stakeholder: "Stakeholder"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

