var EntityLogicalName = "opportunity";
var Form_2e5bb425_abef_4661_9ed7_df5cb28f2ed4_Properties = {
budgetamount: "budgetamount"
,closeprobability: "closeprobability"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,estimatedclosedate: "estimatedclosedate"
,estimatedvalue: "estimatedvalue"
,freightamount: "freightamount"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,msdyn_accountmanagerid: "msdyn_accountmanagerid"
,msdyn_contractorganizationalunitid: "msdyn_contractorganizationalunitid"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,opportunityratingcode: "opportunityratingcode"
,ownerid: "ownerid"
,parentaccountid: "parentaccountid"
,parentcontactid: "parentcontactid"
,pricelevelid: "pricelevelid"
,proposedsolution: "proposedsolution"
,purchaseprocess: "purchaseprocess"
,purchasetimeframe: "purchasetimeframe"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_2e5bb425_abef_4661_9ed7_df5cb28f2ed4_Controls = {
budgetamount: "budgetamount"
,closeprobability: "closeprobability"
,Competitors: "Competitors"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,freightamount: "freightamount"
,header_estimatedclosedate: "header_estimatedclosedate"
,header_estimatedvalue: "header_estimatedvalue"
,header_ownerid: "header_ownerid"
,header_statuscode: "header_statuscode"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,msdyn_accountmanagerid: "msdyn_accountmanagerid"
,msdyn_contractorganizationalunitid: "msdyn_contractorganizationalunitid"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,notescontrol: "notescontrol"
,opportunityproductsGrid: "opportunityproductsGrid"
,opportunityratingcode: "opportunityratingcode"
,parentaccountid: "parentaccountid"
,parentcontactid: "parentcontactid"
,pricelevelid: "pricelevelid"
,ProductSuggestions_LinkControl: "ProductSuggestions_LinkControl"
,ProjectLinesGrid: "ProjectLinesGrid"
,proposedsolution: "proposedsolution"
,purchaseprocess: "purchaseprocess"
,purchasetimeframe: "purchasetimeframe"
,Pursuit_Team: "Pursuit_Team"
,quote: "quote"
,Stakeholders: "Stakeholders"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

