var EntityLogicalName = "opportunity";
var Form_8335a04b_dc80_44b0_83ab_11ed80f93d3e_Properties = {
budgetamount: "budgetamount"
,closeprobability: "closeprobability"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,estimatedclosedate: "estimatedclosedate"
,estimatedvalue: "estimatedvalue"
,freightamount: "freightamount"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_workordertype: "msdyn_workordertype"
,name: "name"
,opportunityratingcode: "opportunityratingcode"
,ownerid: "ownerid"
,parentaccountid: "parentaccountid"
,parentcontactid: "parentcontactid"
,pricelevelid: "pricelevelid"
,proposedsolution: "proposedsolution"
,purchaseprocess: "purchaseprocess"
,purchasetimeframe: "purchasetimeframe"
,salesstagecode: "salesstagecode"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_8335a04b_dc80_44b0_83ab_11ed80f93d3e_Controls = {
budgetamount: "budgetamount"
,closeprobability: "closeprobability"
,Competitors: "Competitors"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,freightamount: "freightamount"
,header_estimatedclosedate: "header_estimatedclosedate"
,header_estimatedvalue: "header_estimatedvalue"
,header_ownerid: "header_ownerid"
,header_statuscode: "header_statuscode"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_workordertype: "msdyn_workordertype"
,name: "name"
,notescontrol: "notescontrol"
,opportunityproductsGrid: "opportunityproductsGrid"
,opportunityratingcode: "opportunityratingcode"
,OpportunityServicesGrid: "OpportunityServicesGrid"
,parentaccountid: "parentaccountid"
,parentcontactid: "parentcontactid"
,pricelevelid: "pricelevelid"
,proposedsolution: "proposedsolution"
,purchaseprocess: "purchaseprocess"
,purchasetimeframe: "purchasetimeframe"
,Pursuit_Team: "Pursuit_Team"
,quote: "quote"
,salesstagecode: "salesstagecode"
,Stakeholders: "Stakeholders"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

