var EntityLogicalName = "salesorder";
var Form_578e22c0_2084_490d_8019_4b55dbbfadc9_Properties = {
billto_composite: "billto_composite"
,billto_contactname: "billto_contactname"
,customerid: "customerid"
,datefulfilled: "datefulfilled"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,ispricelocked: "ispricelocked"
,msdyn_account: "msdyn_account"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,opportunityid: "opportunityid"
,ordernumber: "ordernumber"
,ownerid: "ownerid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,quoteid: "quoteid"
,requestdeliveryby: "requestdeliveryby"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

var Form_578e22c0_2084_490d_8019_4b55dbbfadc9_Controls = {
billto_composite: "billto_composite"
,billto_contactname: "billto_contactname"
,customerid: "customerid"
,datefulfilled: "datefulfilled"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,header_ownerid: "header_ownerid"
,header_statecode: "header_statecode"
,header_statuscode: "header_statuscode"
,header_totalamount: "header_totalamount"
,ispricelocked: "ispricelocked"
,msdyn_account: "msdyn_account"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,notescontrol: "notescontrol"
,opportunityid: "opportunityid"
,ordernumber: "ordernumber"
,OrderServicesGrid: "OrderServicesGrid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,quoteid: "quoteid"
,requestdeliveryby: "requestdeliveryby"
,salesorderdetailsGrid: "salesorderdetailsGrid"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

