var EntityLogicalName = "salesorder";
var Form_d598792c_3ff0_43f3_b3e3_bbd70b99e1a5_Properties = {
billto_composite: "billto_composite"
,customerid: "customerid"
,datefulfilled: "datefulfilled"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,int_trackingnumber: "int_trackingnumber"
,ispricelocked: "ispricelocked"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,opportunityid: "opportunityid"
,ordernumber: "ordernumber"
,ownerid: "ownerid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,quoteid: "quoteid"
,requestdeliveryby: "requestdeliveryby"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,statuscode: "statuscode"
,submitdate: "submitdate"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

var Form_d598792c_3ff0_43f3_b3e3_bbd70b99e1a5_Controls = {
billto_composite: "billto_composite"
,customerid: "customerid"
,datefulfilled: "datefulfilled"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,header_ownerid: "header_ownerid"
,header_statecode: "header_statecode"
,header_statuscode: "header_statuscode"
,header_totalamount: "header_totalamount"
,int_trackingnumber: "int_trackingnumber"
,ispricelocked: "ispricelocked"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,notescontrol: "notescontrol"
,opportunityid: "opportunityid"
,ordernumber: "ordernumber"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,ProductSuggestions_LinkControl: "ProductSuggestions_LinkControl"
,quoteid: "quoteid"
,requestdeliveryby: "requestdeliveryby"
,salesorderdetailsGrid: "salesorderdetailsGrid"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,submitdate: "submitdate"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

