var EntityLogicalName = "salesorder";
var Form_37cf3265_b01e_43a4_9e9e_349bf0f59195_Properties = {
billto_composite: "billto_composite"
,billto_contactname: "billto_contactname"
,customerid: "customerid"
,freighttermscode: "freighttermscode"
,ispricelocked: "ispricelocked"
,msdyn_accountmanagerid: "msdyn_accountmanagerid"
,msdyn_contractorganizationalunitid: "msdyn_contractorganizationalunitid"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_psastate: "msdyn_psastate"
,msdyn_psastatusreason: "msdyn_psastatusreason"
,name: "name"
,opportunityid: "opportunityid"
,ordernumber: "ordernumber"
,ownerid: "ownerid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,quoteid: "quoteid"
,requestdeliveryby: "requestdeliveryby"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,totalamount: "totalamount"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

var Form_37cf3265_b01e_43a4_9e9e_349bf0f59195_Controls = {
billto_composite: "billto_composite"
,billto_contactname: "billto_contactname"
,customerid: "customerid"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,freighttermscode: "freighttermscode"
,header_msdyn_psastate: "header_msdyn_psastate"
,header_msdyn_psastatusreason: "header_msdyn_psastatusreason"
,header_ownerid: "header_ownerid"
,header_totalamount: "header_totalamount"
,ispricelocked: "ispricelocked"
,msdyn_accountmanagerid: "msdyn_accountmanagerid"
,msdyn_contractorganizationalunitid: "msdyn_contractorganizationalunitid"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_psastatusreason: "msdyn_psastatusreason"
,name: "name"
,notescontrol: "notescontrol"
,opportunityid: "opportunityid"
,ordernumber: "ordernumber"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,ProductSuggestions_LinkControl: "ProductSuggestions_LinkControl"
,ProjectContractLines: "ProjectContractLines"
,quoteid: "quoteid"
,requestdeliveryby: "requestdeliveryby"
,salesorderdetailsGrid: "salesorderdetailsGrid"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,transactioncurrencyid: "transactioncurrencyid"
,WebResource_ContractPerformance: "WebResource_ContractPerformance"
,WebResource_KPIBilling: "WebResource_KPIBilling"
,WebResource_KPIEffort: "WebResource_KPIEffort"
,willcall: "willcall"
};

