var EntityLogicalName = "salesorderdetail";
var Form_1b85d96c_5449_4c87_bb96_500150a15faf_Properties = {
baseamount: "baseamount"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,msdyn_agreement: "msdyn_agreement"
,msdyn_linetype: "msdyn_linetype"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,quantity: "quantity"
,quantitybackordered: "quantitybackordered"
,quantitycancelled: "quantitycancelled"
,quantityshipped: "quantityshipped"
,requestdeliveryby: "requestdeliveryby"
,salesrepid: "salesrepid"
,shipto_city: "shipto_city"
,shipto_contactname: "shipto_contactname"
,shipto_country: "shipto_country"
,shipto_fax: "shipto_fax"
,shipto_freighttermscode: "shipto_freighttermscode"
,shipto_line1: "shipto_line1"
,shipto_line2: "shipto_line2"
,shipto_line3: "shipto_line3"
,shipto_name: "shipto_name"
,shipto_postalcode: "shipto_postalcode"
,shipto_stateorprovince: "shipto_stateorprovince"
,shipto_telephone: "shipto_telephone"
,tax: "tax"
,transactioncurrencyid: "transactioncurrencyid"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
,willcall: "willcall"
};

var Form_1b85d96c_5449_4c87_bb96_500150a15faf_Controls = {
baseamount: "baseamount"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,msdyn_agreement: "msdyn_agreement"
,msdyn_linetype: "msdyn_linetype"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,quantity: "quantity"
,quantitybackordered: "quantitybackordered"
,quantitycancelled: "quantitycancelled"
,quantityshipped: "quantityshipped"
,requestdeliveryby: "requestdeliveryby"
,salesrepid: "salesrepid"
,shipto_city: "shipto_city"
,shipto_contactname: "shipto_contactname"
,shipto_country: "shipto_country"
,shipto_fax: "shipto_fax"
,shipto_freighttermscode: "shipto_freighttermscode"
,shipto_line1: "shipto_line1"
,shipto_line2: "shipto_line2"
,shipto_line3: "shipto_line3"
,shipto_name: "shipto_name"
,shipto_postalcode: "shipto_postalcode"
,shipto_stateorprovince: "shipto_stateorprovince"
,shipto_telephone: "shipto_telephone"
,tax: "tax"
,transactioncurrencyid: "transactioncurrencyid"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
,willcall: "willcall"
};

