var EntityLogicalName = "plugintracelog";
var Form_95705278_fa02_49d0_8e02_9ad7791a096f_Properties = {
configuration: "configuration"
,correlationid: "correlationid"
,depth: "depth"
,exceptiondetails: "exceptiondetails"
,issystemcreated: "issystemcreated"
,messageblock: "messageblock"
,messagename: "messagename"
,mode: "mode"
,operationtype: "operationtype"
,performanceexecutionduration: "performanceexecutionduration"
,performanceexecutionstarttime: "performanceexecutionstarttime"
,persistencekey: "persistencekey"
,pluginstepid: "pluginstepid"
,primaryentity: "primaryentity"
,requestid: "requestid"
,secureconfiguration: "secureconfiguration"
,typename: "typename"
};

var Form_95705278_fa02_49d0_8e02_9ad7791a096f_Controls = {
configuration: "configuration"
,correlationid: "correlationid"
,depth: "depth"
,exceptiondetails: "exceptiondetails"
,header_messagename: "header_messagename"
,header_operationtype: "header_operationtype"
,header_primaryentity: "header_primaryentity"
,issystemcreated: "issystemcreated"
,messageblock: "messageblock"
,messagename: "messagename"
,mode: "mode"
,operationtype: "operationtype"
,performanceexecutionduration: "performanceexecutionduration"
,performanceexecutionstarttime: "performanceexecutionstarttime"
,persistencekey: "persistencekey"
,pluginstepid: "pluginstepid"
,primaryentity: "primaryentity"
,requestid: "requestid"
,secureconfiguration: "secureconfiguration"
,typename: "typename"
};

