var EntityLogicalName = "product";
var Form_a640be62_63f6_4027_90d7_48c014a7c6f3_Properties = {
defaultuomid: "defaultuomid"
,defaultuomscheduleid: "defaultuomscheduleid"
,description: "description"
,msdyn_converttocustomerasset: "msdyn_converttocustomerasset"
,msdyn_defaultvendor: "msdyn_defaultvendor"
,msdyn_fieldserviceproducttype: "msdyn_fieldserviceproducttype"
,msdyn_purchasename: "msdyn_purchasename"
,msdyn_taxable: "msdyn_taxable"
,msdyn_upccode: "msdyn_upccode"
,name: "name"
,parentproductid: "parentproductid"
,pricelevelid: "pricelevelid"
,productnumber: "productnumber"
,quantitydecimal: "quantitydecimal"
,statecode: "statecode"
,subjectid: "subjectid"
,validfromdate: "validfromdate"
,validtodate: "validtodate"
};

var Form_a640be62_63f6_4027_90d7_48c014a7c6f3_Controls = {
defaultuomid: "defaultuomid"
,defaultuomscheduleid: "defaultuomscheduleid"
,description: "description"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,header_statecode: "header_statecode"
,msdyn_converttocustomerasset: "msdyn_converttocustomerasset"
,msdyn_defaultvendor: "msdyn_defaultvendor"
,msdyn_fieldserviceproducttype: "msdyn_fieldserviceproducttype"
,msdyn_purchasename: "msdyn_purchasename"
,msdyn_taxable: "msdyn_taxable"
,msdyn_upccode: "msdyn_upccode"
,name: "name"
,notescontrol: "notescontrol"
,parentproductid: "parentproductid"
,Price_List_Items: "Price_List_Items"
,pricelevelid: "pricelevelid"
,product_dynamic_properties: "product_dynamic_properties"
,productassocaition_items: "productassocaition_items"
,productnumber: "productnumber"
,productsubstitute_items: "productsubstitute_items"
,quantitydecimal: "quantitydecimal"
,subjectid: "subjectid"
,validfromdate: "validfromdate"
,validtodate: "validtodate"
};

