var EntityLogicalName = "product";
var Form_6af59e16_86c9_4ae0_94f3_3d571de2cf23_Properties = {
currentcost: "currentcost"
,defaultuomid: "defaultuomid"
,defaultuomscheduleid: "defaultuomscheduleid"
,description: "description"
,name: "name"
,parentproductid: "parentproductid"
,price: "price"
,pricelevelid: "pricelevelid"
,productnumber: "productnumber"
,quantitydecimal: "quantitydecimal"
,standardcost: "standardcost"
,statecode: "statecode"
,subjectid: "subjectid"
,validfromdate: "validfromdate"
,validtodate: "validtodate"
};

var Form_6af59e16_86c9_4ae0_94f3_3d571de2cf23_Controls = {
Computed_Fields: "Computed_Fields"
,currentcost: "currentcost"
,defaultuomid: "defaultuomid"
,defaultuomscheduleid: "defaultuomscheduleid"
,description: "description"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,header_statecode: "header_statecode"
,name: "name"
,notescontrol: "notescontrol"
,parentproductid: "parentproductid"
,price: "price"
,Price_List_Items: "Price_List_Items"
,pricelevelid: "pricelevelid"
,product_dynamic_properties: "product_dynamic_properties"
,productassocaition_items: "productassocaition_items"
,productnumber: "productnumber"
,productsubstitute_items: "productsubstitute_items"
,quantitydecimal: "quantitydecimal"
,standardcost: "standardcost"
,subjectid: "subjectid"
,validfromdate: "validfromdate"
,validtodate: "validtodate"
};

