var EntityLogicalName = "product";
var Form_42805efb_1f65_4ae8_91bc_618967a55c6e_Properties = {
currentcost: "currentcost"
,defaultuomid: "defaultuomid"
,defaultuomscheduleid: "defaultuomscheduleid"
,description: "description"
,name: "name"
,price: "price"
,pricelevelid: "pricelevelid"
,productnumber: "productnumber"
,producttypecode: "producttypecode"
,producturl: "producturl"
,quantitydecimal: "quantitydecimal"
,quantityonhand: "quantityonhand"
,standardcost: "standardcost"
,stockvolume: "stockvolume"
,stockweight: "stockweight"
,subjectid: "subjectid"
,transactioncurrencyid: "transactioncurrencyid"
,vendorname: "vendorname"
,vendorpartnumber: "vendorpartnumber"
};

var Form_42805efb_1f65_4ae8_91bc_618967a55c6e_Controls = {
currentcost: "currentcost"
,defaultuomid: "defaultuomid"
,defaultuomscheduleid: "defaultuomscheduleid"
,description: "description"
,name: "name"
,notescontrol: "notescontrol"
,price: "price"
,pricelevelid: "pricelevelid"
,productnumber: "productnumber"
,producttypecode: "producttypecode"
,producturl: "producturl"
,quantitydecimal: "quantitydecimal"
,quantityonhand: "quantityonhand"
,standardcost: "standardcost"
,stockvolume: "stockvolume"
,stockweight: "stockweight"
,subjectid: "subjectid"
,transactioncurrencyid: "transactioncurrencyid"
,vendorname: "vendorname"
,vendorpartnumber: "vendorpartnumber"
};

