var EntityLogicalName = "msdyn_project";
var Form_105ef076_a72a_4382_bde5_35e3c3d9db40_Properties = {
msdyn_actualend: "msdyn_actualend"
,msdyn_actualhours: "msdyn_actualhours"
,msdyn_actualstart: "msdyn_actualstart"
,msdyn_comments: "msdyn_comments"
,msdyn_contractorganizationalunitid: "msdyn_contractorganizationalunitid"
,msdyn_costconsumption: "msdyn_costconsumption"
,msdyn_costperformence: "msdyn_costperformence"
,msdyn_customer: "msdyn_customer"
,msdyn_description: "msdyn_description"
,msdyn_istemplate: "msdyn_istemplate"
,msdyn_overallprojectstatus: "msdyn_overallprojectstatus"
,msdyn_plannedhours: "msdyn_plannedhours"
,msdyn_progress: "msdyn_progress"
,msdyn_projectmanager: "msdyn_projectmanager"
,msdyn_projecttemplate: "msdyn_projecttemplate"
,msdyn_scheduledend: "msdyn_scheduledend"
,msdyn_scheduledstart: "msdyn_scheduledstart"
,msdyn_scheduleperformance: "msdyn_scheduleperformance"
,msdyn_statusupdatedon: "msdyn_statusupdatedon"
,msdyn_subject: "msdyn_subject"
,msdyn_totalactualcost: "msdyn_totalactualcost"
,msdyn_totalplannedcost: "msdyn_totalplannedcost"
,msdyn_workhourtemplate: "msdyn_workhourtemplate"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_105ef076_a72a_4382_bde5_35e3c3d9db40_Controls = {
header_msdyn_costconsumption: "header_msdyn_costconsumption"
,header_msdyn_progress: "header_msdyn_progress"
,header_msdyn_totalplannedcost: "header_msdyn_totalplannedcost"
,header_scheduledend: "header_scheduledend"
,msdyn_actualend: "msdyn_actualend"
,msdyn_actualhours: "msdyn_actualhours"
,msdyn_actualstart: "msdyn_actualstart"
,msdyn_comments: "msdyn_comments"
,msdyn_contractorganizationalunitid: "msdyn_contractorganizationalunitid"
,msdyn_costperformence: "msdyn_costperformence"
,msdyn_customer: "msdyn_customer"
,msdyn_description: "msdyn_description"
,msdyn_istemplate: "msdyn_istemplate"
,msdyn_overallprojectstatus: "msdyn_overallprojectstatus"
,msdyn_plannedhours: "msdyn_plannedhours"
,msdyn_projectmanager: "msdyn_projectmanager"
,msdyn_projecttemplate: "msdyn_projecttemplate"
,msdyn_scheduledend: "msdyn_scheduledend"
,msdyn_scheduledstart: "msdyn_scheduledstart"
,msdyn_scheduleperformance: "msdyn_scheduleperformance"
,msdyn_statusupdatedon: "msdyn_statusupdatedon"
,msdyn_subject: "msdyn_subject"
,msdyn_totalactualcost: "msdyn_totalactualcost"
,msdyn_totalplannedcost: "msdyn_totalplannedcost"
,msdyn_workhourtemplate: "msdyn_workhourtemplate"
,OpportunityLines: "OpportunityLines"
,ownerid: "ownerid"
,ProjectContract: "ProjectContract"
,ProjectQuote: "ProjectQuote"
,SchedulePerformanceCost: "SchedulePerformanceCost"
,SchedulePerformanceEffort: "SchedulePerformanceEffort"
,SubGrid_TeamMember: "SubGrid_TeamMember"
,transactioncurrencyid: "transactioncurrencyid"
,WebResource_CostConsumptionPercent: "WebResource_CostConsumptionPercent"
,WebResource_ProgressPercent: "WebResource_ProgressPercent"
};

