var EntityLogicalName = "dynamicproperty";
var Form_b955ef97_f38a_4412_aa21_adb00a83effc_Properties = {
datatype: "datatype"
,defaultvaluedecimal: "defaultvaluedecimal"
,defaultvaluedouble: "defaultvaluedouble"
,defaultvalueinteger: "defaultvalueinteger"
,defaultvalueoptionset: "defaultvalueoptionset"
,defaultvaluestring: "defaultvaluestring"
,description: "description"
,ishidden: "ishidden"
,isreadonly: "isreadonly"
,isrequired: "isrequired"
,maxlengthstring: "maxlengthstring"
,maxvaluedecimal: "maxvaluedecimal"
,maxvaluedouble: "maxvaluedouble"
,maxvalueinteger: "maxvalueinteger"
,minvaluedecimal: "minvaluedecimal"
,minvaluedouble: "minvaluedouble"
,minvalueinteger: "minvalueinteger"
,name: "name"
,precision: "precision"
,regardingobjectid: "regardingobjectid"
};

var Form_b955ef97_f38a_4412_aa21_adb00a83effc_Controls = {
datatype: "datatype"
,defaultvaluedecimal: "defaultvaluedecimal"
,defaultvaluedouble: "defaultvaluedouble"
,defaultvalueinteger: "defaultvalueinteger"
,defaultvalueoptionset: "defaultvalueoptionset"
,defaultvaluestring: "defaultvaluestring"
,description: "description"
,grid_DynamicPropertyOptionSetItem: "grid_DynamicPropertyOptionSetItem"
,ishidden: "ishidden"
,isreadonly: "isreadonly"
,isrequired: "isrequired"
,maxlengthstring: "maxlengthstring"
,maxvaluedecimal: "maxvaluedecimal"
,maxvaluedouble: "maxvaluedouble"
,maxvalueinteger: "maxvalueinteger"
,minvaluedecimal: "minvaluedecimal"
,minvaluedouble: "minvaluedouble"
,minvalueinteger: "minvalueinteger"
,name: "name"
,precision: "precision"
,regardingobjectid: "regardingobjectid"
};

