var EntityLogicalName = "msdyn_purchaseorder";
var Form_53f3aa73_82fb_433c_b49a_72e1d900229d_Properties = {
msdyn_address1: "msdyn_address1"
,msdyn_address2: "msdyn_address2"
,msdyn_address3: "msdyn_address3"
,msdyn_amountbilled: "msdyn_amountbilled"
,msdyn_approvalstatus: "msdyn_approvalstatus"
,msdyn_approvedrejectedby: "msdyn_approvedrejectedby"
,msdyn_booking: "msdyn_booking"
,msdyn_city: "msdyn_city"
,msdyn_country: "msdyn_country"
,msdyn_dateexpected: "msdyn_dateexpected"
,msdyn_name: "msdyn_name"
,msdyn_orderedby: "msdyn_orderedby"
,msdyn_paymentterm: "msdyn_paymentterm"
,msdyn_postalcode: "msdyn_postalcode"
,msdyn_purchaseorderdate: "msdyn_purchaseorderdate"
,msdyn_receivetowarehouse: "msdyn_receivetowarehouse"
,msdyn_requestedbyresource: "msdyn_requestedbyresource"
,msdyn_shipto: "msdyn_shipto"
,msdyn_shipvia: "msdyn_shipvia"
,msdyn_stateorprovince: "msdyn_stateorprovince"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_vendor: "msdyn_vendor"
,msdyn_vendornote: "msdyn_vendornote"
,msdyn_workorder: "msdyn_workorder"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_53f3aa73_82fb_433c_b49a_72e1d900229d_Controls = {
BILLS: "BILLS"
,msdyn_address1: "msdyn_address1"
,msdyn_address2: "msdyn_address2"
,msdyn_address3: "msdyn_address3"
,msdyn_amountbilled: "msdyn_amountbilled"
,msdyn_approvalstatus: "msdyn_approvalstatus"
,msdyn_approvedrejectedby: "msdyn_approvedrejectedby"
,msdyn_booking: "msdyn_booking"
,msdyn_city: "msdyn_city"
,msdyn_country: "msdyn_country"
,msdyn_dateexpected: "msdyn_dateexpected"
,msdyn_name: "msdyn_name"
,msdyn_orderedby: "msdyn_orderedby"
,msdyn_paymentterm: "msdyn_paymentterm"
,msdyn_postalcode: "msdyn_postalcode"
,msdyn_purchaseorderdate: "msdyn_purchaseorderdate"
,msdyn_receivetowarehouse: "msdyn_receivetowarehouse"
,msdyn_requestedbyresource: "msdyn_requestedbyresource"
,msdyn_shipto: "msdyn_shipto"
,msdyn_shipvia: "msdyn_shipvia"
,msdyn_stateorprovince: "msdyn_stateorprovince"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_vendor: "msdyn_vendor"
,msdyn_vendornote: "msdyn_vendornote"
,msdyn_workorder: "msdyn_workorder"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,PurchaseOrderProductsGrid: "PurchaseOrderProductsGrid"
,RECEIPT_PRODUCTS: "RECEIPT_PRODUCTS"
,RECEIPTS: "RECEIPTS"
,transactioncurrencyid: "transactioncurrencyid"
};

