var EntityLogicalName = "msdyn_purchaseorderproduct";
var Form_420361fb_c2fd_44ee_bde9_e8f2f1339480_Properties = {
msdyn_associatetobooking: "msdyn_associatetobooking"
,msdyn_associatetowarehouse: "msdyn_associatetowarehouse"
,msdyn_associatetoworkorder: "msdyn_associatetoworkorder"
,msdyn_dateexpected: "msdyn_dateexpected"
,msdyn_description: "msdyn_description"
,msdyn_itemstatus: "msdyn_itemstatus"
,msdyn_lineorder: "msdyn_lineorder"
,msdyn_name: "msdyn_name"
,msdyn_product: "msdyn_product"
,msdyn_purchaseorder: "msdyn_purchaseorder"
,msdyn_qtybilled: "msdyn_qtybilled"
,msdyn_qtyreceived: "msdyn_qtyreceived"
,msdyn_quantity: "msdyn_quantity"
,msdyn_totalcost: "msdyn_totalcost"
,msdyn_unit: "msdyn_unit"
,msdyn_unitcost: "msdyn_unitcost"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_420361fb_c2fd_44ee_bde9_e8f2f1339480_Controls = {
msdyn_associatetobooking: "msdyn_associatetobooking"
,msdyn_associatetowarehouse: "msdyn_associatetowarehouse"
,msdyn_associatetoworkorder: "msdyn_associatetoworkorder"
,msdyn_dateexpected: "msdyn_dateexpected"
,msdyn_description: "msdyn_description"
,msdyn_itemstatus: "msdyn_itemstatus"
,msdyn_lineorder: "msdyn_lineorder"
,msdyn_name: "msdyn_name"
,msdyn_product: "msdyn_product"
,msdyn_purchaseorder: "msdyn_purchaseorder"
,msdyn_qtybilled: "msdyn_qtybilled"
,msdyn_qtyreceived: "msdyn_qtyreceived"
,msdyn_quantity: "msdyn_quantity"
,msdyn_totalcost: "msdyn_totalcost"
,msdyn_unit: "msdyn_unit"
,msdyn_unitcost: "msdyn_unitcost"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

