var EntityLogicalName = "msdyn_quotebookingsetup";
var Form_d316fdb5_c1b2_4ffe_b47d_c4ec1153f926_Properties = {
msdyn_description: "msdyn_description"
,msdyn_estimatedcost: "msdyn_estimatedcost"
,msdyn_estimatedmargin: "msdyn_estimatedmargin"
,msdyn_estimatedmarginperwo: "msdyn_estimatedmarginperwo"
,msdyn_estimatedproductcost: "msdyn_estimatedproductcost"
,msdyn_estimatedproductrevenue: "msdyn_estimatedproductrevenue"
,msdyn_estimatedrevenue: "msdyn_estimatedrevenue"
,msdyn_estimatedrevenueperwo: "msdyn_estimatedrevenueperwo"
,msdyn_estimatedservicecost: "msdyn_estimatedservicecost"
,msdyn_estimatedservicerevenue: "msdyn_estimatedservicerevenue"
,msdyn_name: "msdyn_name"
,msdyn_quote: "msdyn_quote"
,msdyn_quotedetailid: "msdyn_quotedetailid"
,msdyn_recurrencesettings: "msdyn_recurrencesettings"
,msdyn_workordertype: "msdyn_workordertype"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_d316fdb5_c1b2_4ffe_b47d_c4ec1153f926_Controls = {
IncidentsGrid: "IncidentsGrid"
,msdyn_description: "msdyn_description"
,msdyn_estimatedcost: "msdyn_estimatedcost"
,msdyn_estimatedmargin: "msdyn_estimatedmargin"
,msdyn_estimatedmarginperwo: "msdyn_estimatedmarginperwo"
,msdyn_estimatedproductcost: "msdyn_estimatedproductcost"
,msdyn_estimatedproductrevenue: "msdyn_estimatedproductrevenue"
,msdyn_estimatedrevenue: "msdyn_estimatedrevenue"
,msdyn_estimatedrevenueperwo: "msdyn_estimatedrevenueperwo"
,msdyn_estimatedservicecost: "msdyn_estimatedservicecost"
,msdyn_estimatedservicerevenue: "msdyn_estimatedservicerevenue"
,msdyn_name: "msdyn_name"
,msdyn_quote: "msdyn_quote"
,msdyn_quotedetailid: "msdyn_quotedetailid"
,msdyn_recurrencesettings: "msdyn_recurrencesettings"
,msdyn_workordertype: "msdyn_workordertype"
,ownerid: "ownerid"
,productsGrid: "productsGrid"
,ServicesGrid: "ServicesGrid"
,ServiceTasksGrid: "ServiceTasksGrid"
,transactioncurrencyid: "transactioncurrencyid"
};

