var EntityLogicalName = "quote";
var Form_54076a2d_d043_4a1b_b061_4d06846371a9_Properties = {
billto_composite: "billto_composite"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,effectivefrom: "effectivefrom"
,effectiveto: "effectiveto"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,opportunityid: "opportunityid"
,ownerid: "ownerid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,quotenumber: "quotenumber"
,revisionnumber: "revisionnumber"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

var Form_54076a2d_d043_4a1b_b061_4d06846371a9_Controls = {
billto_composite: "billto_composite"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,header_effectivefrom: "header_effectivefrom"
,header_effectiveto: "header_effectiveto"
,header_ownerid: "header_ownerid"
,header_totalamount: "header_totalamount"
,msdyn_ordertype: "msdyn_ordertype"
,name: "name"
,notescontrol: "notescontrol"
,opportunityid: "opportunityid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,ProductSuggestions_LinkControl: "ProductSuggestions_LinkControl"
,quotedetailsGrid: "quotedetailsGrid"
,quotenumber: "quotenumber"
,revisionnumber: "revisionnumber"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

