var EntityLogicalName = "quote";
var Form_b3fa6477_581b_411f_a725_0ab32d8edb8f_Properties = {
billto_composite: "billto_composite"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,effectivefrom: "effectivefrom"
,effectiveto: "effectiveto"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,msdyn_account: "msdyn_account"
,msdyn_estimatedcost: "msdyn_estimatedcost"
,msdyn_estimatedquotemargin: "msdyn_estimatedquotemargin"
,msdyn_invoicesetuptotals: "msdyn_invoicesetuptotals"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_totalamount: "msdyn_totalamount"
,name: "name"
,opportunityid: "opportunityid"
,ownerid: "ownerid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,quotenumber: "quotenumber"
,revisionnumber: "revisionnumber"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

var Form_b3fa6477_581b_411f_a725_0ab32d8edb8f_Controls = {
billto_composite: "billto_composite"
,customerid: "customerid"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,effectiveto: "effectiveto"
,freightamount: "freightamount"
,freighttermscode: "freighttermscode"
,header_effectivefrom: "header_effectivefrom"
,header_effectiveto: "header_effectiveto"
,header_msdyn_totalamount: "header_msdyn_totalamount"
,header_ownerid: "header_ownerid"
,msdyn_account: "msdyn_account"
,msdyn_estimatedcost: "msdyn_estimatedcost"
,msdyn_estimatedquotemargin: "msdyn_estimatedquotemargin"
,msdyn_invoicesetuptotals: "msdyn_invoicesetuptotals"
,msdyn_ordertype: "msdyn_ordertype"
,msdyn_totalamount: "msdyn_totalamount"
,name: "name"
,notescontrol: "notescontrol"
,opportunityid: "opportunityid"
,paymenttermscode: "paymenttermscode"
,pricelevelid: "pricelevelid"
,quotedetailsGrid: "quotedetailsGrid"
,quotenumber: "quotenumber"
,revisionnumber: "revisionnumber"
,servicesGrid: "servicesGrid"
,shippingmethodcode: "shippingmethodcode"
,shipto_composite: "shipto_composite"
,statecode: "statecode"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
,willcall: "willcall"
};

