var EntityLogicalName = "msdyn_resourcerequirement";
var Form_bc534926_8fba_4265_bada_bff18ff0872e_Properties = {
msdyn_allocationmethod: "msdyn_allocationmethod"
,msdyn_calendarid: "msdyn_calendarid"
,msdyn_city: "msdyn_city"
,msdyn_costprice: "msdyn_costprice"
,msdyn_country: "msdyn_country"
,msdyn_duration: "msdyn_duration"
,msdyn_fromdate: "msdyn_fromdate"
,msdyn_isprimary: "msdyn_isprimary"
,msdyn_latitude: "msdyn_latitude"
,msdyn_longitude: "msdyn_longitude"
,msdyn_name: "msdyn_name"
,msdyn_percentage: "msdyn_percentage"
,msdyn_priority: "msdyn_priority"
,msdyn_projectid: "msdyn_projectid"
,msdyn_requeststatus: "msdyn_requeststatus"
,msdyn_stateorprovince: "msdyn_stateorprovince"
,msdyn_status: "msdyn_status"
,msdyn_territory: "msdyn_territory"
,msdyn_timefrompromised: "msdyn_timefrompromised"
,msdyn_timegroup: "msdyn_timegroup"
,msdyn_timetopromised: "msdyn_timetopromised"
,msdyn_timewindowend: "msdyn_timewindowend"
,msdyn_timewindowstart: "msdyn_timewindowstart"
,msdyn_todate: "msdyn_todate"
,msdyn_workhourtemplate: "msdyn_workhourtemplate"
,msdyn_worklocation: "msdyn_worklocation"
,msdyn_workorder: "msdyn_workorder"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_bc534926_8fba_4265_bada_bff18ff0872e_Controls = {
IFRAME_AvailabilityView: "IFRAME_AvailabilityView"
,msdyn_allocationmethod: "msdyn_allocationmethod"
,msdyn_calendarid: "msdyn_calendarid"
,msdyn_city: "msdyn_city"
,msdyn_costprice: "msdyn_costprice"
,msdyn_country: "msdyn_country"
,msdyn_duration: "msdyn_duration"
,msdyn_fromdate: "msdyn_fromdate"
,msdyn_isprimary: "msdyn_isprimary"
,msdyn_latitude: "msdyn_latitude"
,msdyn_longitude: "msdyn_longitude"
,msdyn_name: "msdyn_name"
,msdyn_percentage: "msdyn_percentage"
,msdyn_priority: "msdyn_priority"
,msdyn_projectid: "msdyn_projectid"
,msdyn_requeststatus: "msdyn_requeststatus"
,msdyn_stateorprovince: "msdyn_stateorprovince"
,msdyn_status: "msdyn_status"
,msdyn_territory: "msdyn_territory"
,msdyn_timefrompromised: "msdyn_timefrompromised"
,msdyn_timegroup: "msdyn_timegroup"
,msdyn_timetopromised: "msdyn_timetopromised"
,msdyn_timewindowend: "msdyn_timewindowend"
,msdyn_timewindowstart: "msdyn_timewindowstart"
,msdyn_todate: "msdyn_todate"
,msdyn_workhourtemplate: "msdyn_workhourtemplate"
,msdyn_worklocation: "msdyn_worklocation"
,msdyn_workorder: "msdyn_workorder"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,RequirementCharacteristics: "RequirementCharacteristics"
,RequirementOrganizationUnit: "RequirementOrganizationUnit"
,RequirementResourceCategory: "RequirementResourceCategory"
,RequirementResourcePreferences: "RequirementResourcePreferences"
,SubGrid_ResourceBookings: "SubGrid_ResourceBookings"
,transactioncurrencyid: "transactioncurrencyid"
,WebResource_msdyn_timewindowend: "WebResource_msdyn_timewindowend"
,WebResource_msdyn_timewindowstart: "WebResource_msdyn_timewindowstart"
};

