var EntityLogicalName = "msdyn_rmaproduct";
var Form_061c93c1_a0dc_4eee_858c_b9d90ce75d75_Properties = {
msdyn_changeownership: "msdyn_changeownership"
,msdyn_credittoaccount: "msdyn_credittoaccount"
,msdyn_customerasset: "msdyn_customerasset"
,msdyn_description: "msdyn_description"
,msdyn_itemstatus: "msdyn_itemstatus"
,msdyn_lineorder: "msdyn_lineorder"
,msdyn_name: "msdyn_name"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_processingaction: "msdyn_processingaction"
,msdyn_product: "msdyn_product"
,msdyn_qtyprocessed: "msdyn_qtyprocessed"
,msdyn_qtyreceived: "msdyn_qtyreceived"
,msdyn_quantitytoreturn: "msdyn_quantitytoreturn"
,msdyn_returntovendor: "msdyn_returntovendor"
,msdyn_returntowarehouse: "msdyn_returntowarehouse"
,msdyn_rma: "msdyn_rma"
,msdyn_taxable: "msdyn_taxable"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_unit: "msdyn_unit"
,msdyn_unitamount: "msdyn_unitamount"
,msdyn_woproduct: "msdyn_woproduct"
,ownerid: "ownerid"
,statecode: "statecode"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_061c93c1_a0dc_4eee_858c_b9d90ce75d75_Controls = {
footer_statecode: "footer_statecode"
,msdyn_changeownership: "msdyn_changeownership"
,msdyn_credittoaccount: "msdyn_credittoaccount"
,msdyn_customerasset: "msdyn_customerasset"
,msdyn_description: "msdyn_description"
,msdyn_itemstatus: "msdyn_itemstatus"
,msdyn_lineorder: "msdyn_lineorder"
,msdyn_name: "msdyn_name"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_processingaction: "msdyn_processingaction"
,msdyn_product: "msdyn_product"
,msdyn_qtyprocessed: "msdyn_qtyprocessed"
,msdyn_qtyreceived: "msdyn_qtyreceived"
,msdyn_quantitytoreturn: "msdyn_quantitytoreturn"
,msdyn_returntovendor: "msdyn_returntovendor"
,msdyn_returntowarehouse: "msdyn_returntowarehouse"
,msdyn_rma: "msdyn_rma"
,msdyn_taxable: "msdyn_taxable"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_unit: "msdyn_unit"
,msdyn_unitamount: "msdyn_unitamount"
,msdyn_woproduct: "msdyn_woproduct"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

