var EntityLogicalName = "msdyn_rma";
var Form_eebf7d5a_f47b_4d71_a164_583d6d5519a7_Properties = {
msdyn_approvedby: "msdyn_approvedby"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_daterequested: "msdyn_daterequested"
,msdyn_description: "msdyn_description"
,msdyn_eta: "msdyn_eta"
,msdyn_name: "msdyn_name"
,msdyn_packagingtrackingno: "msdyn_packagingtrackingno"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_processingaction: "msdyn_processingaction"
,msdyn_referenceno: "msdyn_referenceno"
,msdyn_requestedbycontact: "msdyn_requestedbycontact"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_shippingtrackingno: "msdyn_shippingtrackingno"
,msdyn_shipvia: "msdyn_shipvia"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,msdyn_taxcode: "msdyn_taxcode"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_workorder: "msdyn_workorder"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_eebf7d5a_f47b_4d71_a164_583d6d5519a7_Controls = {
msdyn_approvedby: "msdyn_approvedby"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_daterequested: "msdyn_daterequested"
,msdyn_description: "msdyn_description"
,msdyn_eta: "msdyn_eta"
,msdyn_name: "msdyn_name"
,msdyn_packagingtrackingno: "msdyn_packagingtrackingno"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_processingaction: "msdyn_processingaction"
,msdyn_referenceno: "msdyn_referenceno"
,msdyn_requestedbycontact: "msdyn_requestedbycontact"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_shippingtrackingno: "msdyn_shippingtrackingno"
,msdyn_shipvia: "msdyn_shipvia"
,msdyn_substatus: "msdyn_substatus"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,msdyn_taxcode: "msdyn_taxcode"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_workorder: "msdyn_workorder"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,receiptsgrid: "receiptsgrid"
,rmaproductgrid: "rmaproductgrid"
,rmaproductsgrid: "rmaproductsgrid"
,transactioncurrencyid: "transactioncurrencyid"
};

