var EntityLogicalName = "msdyn_scheduleboardsetting";
var Form_adaa2258_7ec5_4b3c_b024_db8e4bb1a7bb_Properties = {
msdyn_customtabname: "msdyn_customtabname"
,msdyn_customtabwebresource: "msdyn_customtabwebresource"
,msdyn_fullybookedcolor: "msdyn_fullybookedcolor"
,msdyn_hidecancelled: "msdyn_hidecancelled"
,msdyn_issynchronizeresources: "msdyn_issynchronizeresources"
,msdyn_mapviewtabplacement: "msdyn_mapviewtabplacement"
,msdyn_notbookedcolor: "msdyn_notbookedcolor"
,msdyn_ordernumber: "msdyn_ordernumber"
,msdyn_organizationalunittooltipsviewid: "msdyn_organizationalunittooltipsviewid"
,msdyn_organizationalunitviewid: "msdyn_organizationalunitviewid"
,msdyn_overbookedcolor: "msdyn_overbookedcolor"
,msdyn_partiallybookedcolor: "msdyn_partiallybookedcolor"
,msdyn_scheduleralertsview: "msdyn_scheduleralertsview"
,msdyn_schedulerresourcedetailsview: "msdyn_schedulerresourcedetailsview"
,msdyn_schedulerresourcetooltipview: "msdyn_schedulerresourcetooltipview"
,msdyn_settings: "msdyn_settings"
,msdyn_sharetype: "msdyn_sharetype"
,msdyn_tabname: "msdyn_tabname"
,msdyn_unscheduledrequirementsviewid: "msdyn_unscheduledrequirementsviewid"
,msdyn_unscheduledwopagereccount: "msdyn_unscheduledwopagereccount"
,msdyn_workinghourscolor: "msdyn_workinghourscolor"
,ownerid: "ownerid"
,statecode: "statecode"
};

var Form_adaa2258_7ec5_4b3c_b024_db8e4bb1a7bb_Controls = {
footer_statecode: "footer_statecode"
,msdyn_customtabname: "msdyn_customtabname"
,msdyn_customtabwebresource: "msdyn_customtabwebresource"
,msdyn_fullybookedcolor: "msdyn_fullybookedcolor"
,msdyn_hidecancelled: "msdyn_hidecancelled"
,msdyn_issynchronizeresources: "msdyn_issynchronizeresources"
,msdyn_mapviewtabplacement: "msdyn_mapviewtabplacement"
,msdyn_notbookedcolor: "msdyn_notbookedcolor"
,msdyn_ordernumber: "msdyn_ordernumber"
,msdyn_organizationalunittooltipsviewid: "msdyn_organizationalunittooltipsviewid"
,msdyn_organizationalunitviewid: "msdyn_organizationalunitviewid"
,msdyn_overbookedcolor: "msdyn_overbookedcolor"
,msdyn_partiallybookedcolor: "msdyn_partiallybookedcolor"
,msdyn_scheduleralertsview: "msdyn_scheduleralertsview"
,msdyn_schedulerresourcedetailsview: "msdyn_schedulerresourcedetailsview"
,msdyn_schedulerresourcetooltipview: "msdyn_schedulerresourcetooltipview"
,msdyn_settings: "msdyn_settings"
,msdyn_sharetype: "msdyn_sharetype"
,msdyn_tabname: "msdyn_tabname"
,msdyn_unscheduledrequirementsviewid: "msdyn_unscheduledrequirementsviewid"
,msdyn_unscheduledwopagereccount: "msdyn_unscheduledwopagereccount"
,msdyn_workinghourscolor: "msdyn_workinghourscolor"
,ownerid: "ownerid"
,WebResource_FullyBookedColor: "WebResource_FullyBookedColor"
,WebResource_NotBookedColor: "WebResource_NotBookedColor"
,WebResource_OverbookedColor: "WebResource_OverbookedColor"
,WebResource_PartiallyBookedColor: "WebResource_PartiallyBookedColor"
};

