var EntityLogicalName = "systemuser";
var Form_c2cd9e55_d4b4_4b55_9951_16ead79643e5_Properties = {
accessmode: "accessmode"
,address1_composite: "address1_composite"
,address1_fax: "address1_fax"
,address1_latitude: "address1_latitude"
,address1_longitude: "address1_longitude"
,address1_telephone1: "address1_telephone1"
,address1_telephone2: "address1_telephone2"
,address1_telephone3: "address1_telephone3"
,address2_composite: "address2_composite"
,businessunitid: "businessunitid"
,caltype: "caltype"
,defaultmailbox: "defaultmailbox"
,domainname: "domainname"
,fullname: "fullname"
,homephone: "homephone"
,internalemailaddress: "internalemailaddress"
,invitestatuscode: "invitestatuscode"
,isdisabled: "isdisabled"
,mobilealertemail: "mobilealertemail"
,mobilephone: "mobilephone"
,parentsystemuserid: "parentsystemuserid"
,personalemailaddress: "personalemailaddress"
,preferredaddresscode: "preferredaddresscode"
,preferredphonecode: "preferredphonecode"
,queueid: "queueid"
,siteid: "siteid"
,territoryid: "territoryid"
,title: "title"
,windowsliveid: "windowsliveid"
};

var Form_c2cd9e55_d4b4_4b55_9951_16ead79643e5_Controls = {
accessmode: "accessmode"
,address1_composite: "address1_composite"
,address1_fax: "address1_fax"
,address1_latitude: "address1_latitude"
,address1_longitude: "address1_longitude"
,address1_telephone1: "address1_telephone1"
,address1_telephone2: "address1_telephone2"
,address1_telephone3: "address1_telephone3"
,address2_composite: "address2_composite"
,businessunitid: "businessunitid"
,caltype: "caltype"
,defaultmailbox: "defaultmailbox"
,domainname: "domainname"
,footer_isdisabled: "footer_isdisabled"
,fullname: "fullname"
,homephone: "homephone"
,internalemailaddress: "internalemailaddress"
,invitestatuscode: "invitestatuscode"
,mobilealertemail: "mobilealertemail"
,mobilephone: "mobilephone"
,notescontrol: "notescontrol"
,parentsystemuserid: "parentsystemuserid"
,personalemailaddress: "personalemailaddress"
,preferredaddresscode: "preferredaddresscode"
,preferredphonecode: "preferredphonecode"
,PrivateQueuesSubGrid: "PrivateQueuesSubGrid"
,queueid: "queueid"
,siteid: "siteid"
,TeamsSubGrid: "TeamsSubGrid"
,territoryid: "territoryid"
,title: "title"
,windowsliveid: "windowsliveid"
};

