var EntityLogicalName = "msdyn_workorder";
var Form_f25cecf6_2f00_4eab_aeef_d773af32e027_Properties = {
msdyn_address1: "msdyn_address1"
,msdyn_address2: "msdyn_address2"
,msdyn_address3: "msdyn_address3"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_city: "msdyn_city"
,msdyn_country: "msdyn_country"
,msdyn_customerasset: "msdyn_customerasset"
,msdyn_estimatesubtotalamount: "msdyn_estimatesubtotalamount"
,msdyn_instructions: "msdyn_instructions"
,msdyn_name: "msdyn_name"
,msdyn_postalcode: "msdyn_postalcode"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_primaryincidentdescription: "msdyn_primaryincidentdescription"
,msdyn_primaryincidenttype: "msdyn_primaryincidenttype"
,msdyn_priority: "msdyn_priority"
,msdyn_reportedbycontact: "msdyn_reportedbycontact"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_serviceterritory: "msdyn_serviceterritory"
,msdyn_stateorprovince: "msdyn_stateorprovince"
,msdyn_substatus: "msdyn_substatus"
,msdyn_subtotalamount: "msdyn_subtotalamount"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,msdyn_taxcode: "msdyn_taxcode"
,msdyn_timefrompromised: "msdyn_timefrompromised"
,msdyn_timetopromised: "msdyn_timetopromised"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_totalsalestax: "msdyn_totalsalestax"
,msdyn_workordersummary: "msdyn_workordersummary"
,msdyn_workordertype: "msdyn_workordertype"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_f25cecf6_2f00_4eab_aeef_d773af32e027_Controls = {
bookings: "bookings"
,Incidents_List: "Incidents_List"
,msdyn_address1: "msdyn_address1"
,msdyn_address2: "msdyn_address2"
,msdyn_address3: "msdyn_address3"
,msdyn_billingaccount: "msdyn_billingaccount"
,msdyn_city: "msdyn_city"
,msdyn_country: "msdyn_country"
,msdyn_customerasset: "msdyn_customerasset"
,msdyn_estimatesubtotalamount: "msdyn_estimatesubtotalamount"
,msdyn_instructions: "msdyn_instructions"
,msdyn_name: "msdyn_name"
,msdyn_postalcode: "msdyn_postalcode"
,msdyn_pricelist: "msdyn_pricelist"
,msdyn_primaryincidentdescription: "msdyn_primaryincidentdescription"
,msdyn_primaryincidenttype: "msdyn_primaryincidenttype"
,msdyn_priority: "msdyn_priority"
,msdyn_reportedbycontact: "msdyn_reportedbycontact"
,msdyn_serviceaccount: "msdyn_serviceaccount"
,msdyn_serviceterritory: "msdyn_serviceterritory"
,msdyn_stateorprovince: "msdyn_stateorprovince"
,msdyn_substatus: "msdyn_substatus"
,msdyn_subtotalamount: "msdyn_subtotalamount"
,msdyn_systemstatus: "msdyn_systemstatus"
,msdyn_taxable: "msdyn_taxable"
,msdyn_taxcode: "msdyn_taxcode"
,msdyn_timefrompromised: "msdyn_timefrompromised"
,msdyn_timetopromised: "msdyn_timetopromised"
,msdyn_totalamount: "msdyn_totalamount"
,msdyn_totalsalestax: "msdyn_totalsalestax"
,msdyn_workordersummary: "msdyn_workordersummary"
,msdyn_workordertype: "msdyn_workordertype"
,notescontrol: "notescontrol"
,ownerid: "ownerid"
,transactioncurrencyid: "transactioncurrencyid"
,WebResource_BingMap: "WebResource_BingMap"
,workorderproductsgrid: "workorderproductsgrid"
,workorderservicesgrid: "workorderservicesgrid"
,workorderservicetasksgrid: "workorderservicetasksgrid"
};

