// <auto-generated />
using .ProxyClasses;
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.Threading.Tasks;
using System.ComponentModel;

namespace ProxyClasses
{
    [EntityLogicalNameAttribute("externalparty")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XrmToolkit", "4.0")]
    public partial class ExternalParty : BaseProxyClass
    {
        public new const string LogicalName = "externalparty";
        public const int ObjectTypeCode = 3008;
        public const string PrimaryIdAttribute = "externalpartyid";
        public const string PrimaryNameAttribute = "fullname";
        
        static ExternalParty()
        {
            BaseProxyClass.RegisterProxyType(typeof(ExternalParty), "externalparty");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public ExternalParty() : base(new Entity("externalparty")) { }
        public ExternalParty(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<ExternalParty>(); }
        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }
        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }
        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }
        private static Dictionary<string, eNumberOptions> _numberOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }

        ///<summary>
///<para>Logical Name: createdonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
public string CreatedOnBehalfByYomiName
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: owneridname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridname")]
public string OwnerIdName
{
	get { return this.GetPropertyValue<string>("owneridname"); }
}
///<summary>
///<para>Logical Name: createdbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyyominame")]
public string CreatedByYomiName
{
	get { return this.GetPropertyValue<string>("createdbyyominame"); }
}
///<summary>
///<para>Logical Name: modifiedbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyname")]
public string ModifiedByName
{
	get { return this.GetPropertyValue<string>("modifiedbyname"); }
}
///<summary>
///<para>Logical Name: modifiedbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyyominame")]
public string ModifiedByYomiName
{
	get { return this.GetPropertyValue<string>("modifiedbyyominame"); }
}
///<summary>
///<para>Logical Name: owneridtype</para>
///</summary>
[AttributeLogicalNameAttribute("owneridtype")]
public string OwnerIdType
{
	get { return this.GetPropertyValue<string>("owneridtype"); }
	set { this.SetPropertyValue<string>("owneridtype", value, "OwnerIdType"); }
}
///<summary>
///<para>Logical Name: owneridyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridyominame")]
public string OwnerIdYomiName
{
	get { return this.GetPropertyValue<string>("owneridyominame"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
public string ModifiedOnBehalfByYomiName
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: createdbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyname")]
public string CreatedByName
{
	get { return this.GetPropertyValue<string>("createdbyname"); }
}
///<summary>
///<para>Logical Name: createdonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyname")]
public string CreatedOnBehalfByName
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
public string ModifiedOnBehalfByName
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: versionnumber</para>
///</summary>
[AttributeLogicalNameAttribute("versionnumber")]
public int? VersionNumber
{
	get { return this.GetPropertyValue<int?>("versionnumber"); }
}
///<summary>
///<para>Logical Name: transactioncurrencyidname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("transactioncurrencyidname")]
public string TransactionCurrencyIdName
{
	get { return this.GetPropertyValue<string>("transactioncurrencyidname"); }
}
///<summary>
///<para>Logical Name: correlationkey</para>
///<para>Max Length: 300 characters</para>
///</summary>
[AttributeLogicalNameAttribute("correlationkey")]
public string CorrelationKey
{
	get { return this.GetPropertyValue<string>("correlationkey"); }
	set { this.SetPropertyValue("correlationkey", value, 300, "CorrelationKey"); }
}
///<summary>
///<para>Logical Name: createdby</para>
///</summary>
[AttributeLogicalNameAttribute("createdby")]
public EntityReference CreatedBy
{
	get { return this.GetPropertyValue<EntityReference>("createdby"); }
}
///<summary>
///<para>Logical Name: createdonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfby")]
public EntityReference CreatedBy_Delegate
{
	get { return this.GetPropertyValue<EntityReference>("createdonbehalfby"); }
}
///<summary>
///<para>Logical Name: createdon</para>
///</summary>
[AttributeLogicalNameAttribute("createdon")]
public DateTime? CreatedOn
{
	get { return this.GetPropertyValue<DateTime?>("createdon"); }
}
///<summary>
///<para>Logical Name: transactioncurrencyid</para>
///</summary>
[AttributeLogicalNameAttribute("transactioncurrencyid")]
public EntityReference Currency
{
	get { return this.GetPropertyValue<EntityReference>("transactioncurrencyid"); }
	set { this.SetPropertyValue<EntityReference>("transactioncurrencyid", value, "Currency"); }
}
///<summary>
///<para>Logical Name: emailaddress</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("emailaddress")]
public string EmailAddress
{
	get { return this.GetPropertyValue<string>("emailaddress"); }
	set { this.SetPropertyValue("emailaddress", value, 100, "EmailAddress"); }
}
///<summary>
///<para>Logical Name: exchangerate</para>
///<para>Minimum Value: 0.0000000001</para>
///<para>Maximum Value: 100000000000</para>
///<para>Precision: 10</para>
///</summary>
[AttributeLogicalNameAttribute("exchangerate")]
public decimal? ExchangeRate
{
	get { return this.GetPropertyValue<decimal?>("exchangerate"); }
}
///<summary>
///<para>Key Property (Uniqueidentifier)</para>
///<para>Logical Name: externalpartyid</para>
///</summary>
[AttributeLogicalNameAttribute("externalpartyid")]
public Guid ExternalPartyId
{
	get
	{
		return this.Id;
	}
	set
	{
		this.Id = value;
	}
}
///<summary>
///<para>Logical Name: externalpartyidunique</para>
///</summary>
[AttributeLogicalNameAttribute("externalpartyidunique")]
public Guid ExternalPartyUniqueId
{
	get { return this.GetPropertyValue<Guid>("externalpartyidunique"); }
}
///<summary>
///<para>Logical Name: firstname</para>
///<para>Max Length: 64 characters</para>
///</summary>
[AttributeLogicalNameAttribute("firstname")]
public string FirstName
{
	get { return this.GetPropertyValue<string>("firstname"); }
	set { this.SetPropertyValue("firstname", value, 64, "FirstName"); }
}
///<summary>
///<para>Logical Name: fullname</para>
///<para>Max Length: 300 characters</para>
///</summary>
[AttributeLogicalNameAttribute("fullname")]
public string FullName
{
	get { return this.GetPropertyValue<string>("fullname"); }
	set { this.SetPropertyValue("fullname", value, 300, "FullName"); }
}
///<summary>
///<para>Logical Name: importsequencenumber</para>
///<para>Minimum Value: -2147483648</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("importsequencenumber")]
public int? ImportSequenceNumber
{
	get { return this.GetPropertyValue<int?>("importsequencenumber"); }
	set { this.SetPropertyValue("importsequencenumber", (int?)value, (int)-2147483648, (int)2147483647, "ImportSequenceNumber"); }
}
///<summary>
///<para>Logical Name: lastdisabledon</para>
///</summary>
[AttributeLogicalNameAttribute("lastdisabledon")]
public DateTime? LastDisabledOn
{
	get { return this.GetPropertyValue<DateTime?>("lastdisabledon"); }
	set { this.SetPropertyValue<DateTime?>("lastdisabledon", value, "LastDisabledOn"); }
}
///<summary>
///<para>Logical Name: lastenabledon</para>
///</summary>
[AttributeLogicalNameAttribute("lastenabledon")]
public DateTime? LastEnabledOn
{
	get { return this.GetPropertyValue<DateTime?>("lastenabledon"); }
	set { this.SetPropertyValue<DateTime?>("lastenabledon", value, "LastEnabledOn"); }
}
///<summary>
///<para>Logical Name: lastname</para>
///<para>Max Length: 64 characters</para>
///</summary>
[AttributeLogicalNameAttribute("lastname")]
public string LastName
{
	get { return this.GetPropertyValue<string>("lastname"); }
	set { this.SetPropertyValue("lastname", value, 64, "LastName"); }
}
///<summary>
///<para>Logical Name: middlename</para>
///<para>Max Length: 50 characters</para>
///</summary>
[AttributeLogicalNameAttribute("middlename")]
public string MiddleName
{
	get { return this.GetPropertyValue<string>("middlename"); }
	set { this.SetPropertyValue("middlename", value, 50, "MiddleName"); }
}
///<summary>
///<para>Logical Name: modifiedby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedby")]
public EntityReference ModifiedBy
{
	get { return this.GetPropertyValue<EntityReference>("modifiedby"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfby")]
public EntityReference ModifiedBy_Delegate
{
	get { return this.GetPropertyValue<EntityReference>("modifiedonbehalfby"); }
}
///<summary>
///<para>Logical Name: modifiedon</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedon")]
public DateTime? ModifiedOn
{
	get { return this.GetPropertyValue<DateTime?>("modifiedon"); }
}
///<summary>
///<para>Logical Name: ownerid</para>
///</summary>
[AttributeLogicalNameAttribute("ownerid")]
public EntityReference Owner
{
	get { return this.GetPropertyValue<EntityReference>("ownerid"); }
	set { this.SetPropertyValue<EntityReference>("ownerid", value, "Owner"); }
}
///<summary>
///<para>Logical Name: owningbusinessunit</para>
///</summary>
[AttributeLogicalNameAttribute("owningbusinessunit")]
public EntityReference OwningBusinessUnit
{
	get { return this.GetPropertyValue<EntityReference>("owningbusinessunit"); }
}
///<summary>
///<para>Logical Name: owningteam</para>
///</summary>
[AttributeLogicalNameAttribute("owningteam")]
public EntityReference OwningTeam
{
	get { return this.GetPropertyValue<EntityReference>("owningteam"); }
}
///<summary>
///<para>Logical Name: owninguser</para>
///</summary>
[AttributeLogicalNameAttribute("owninguser")]
public EntityReference OwningUser
{
	get { return this.GetPropertyValue<EntityReference>("owninguser"); }
}
///<summary>
///<para>Logical Name: overriddencreatedon</para>
///</summary>
[AttributeLogicalNameAttribute("overriddencreatedon")]
public DateTime? RecordCreatedOn
{
	get { return this.GetPropertyValue<DateTime?>("overriddencreatedon"); }
	set { this.SetPropertyValue<DateTime?>("overriddencreatedon", value, "RecordCreatedOn"); }
}
/// <summary>
///Logical Name: statecode
/// </summary>
[AttributeLogicalNameAttribute("statecode")]
public eStatus? Status
{
	get
	{
		if (Status_OptionSetValue != null) { return (eStatus)Status_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.Status_OptionSetValue = new OptionSetValue((int)value); }
		else this.Status_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statecode</para>
///</summary>
[AttributeLogicalNameAttribute("statecode")]
public OptionSetValue Status_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statecode"); }
	set { this.SetPropertyValue<OptionSetValue>("statecode", value, "Status_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string Status_Text(IOrganizationService Service)
{
	return this.Status_OptionSetValue.GetOptionSetText(Service, this, "statecode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string Status_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.Status_OptionSetValue.Value);
}
/// <summary>
///Logical Name: statuscode
/// </summary>
[AttributeLogicalNameAttribute("statuscode")]
public eStatusReason? StatusReason
{
	get
	{
		if (StatusReason_OptionSetValue != null) { return (eStatusReason)StatusReason_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.StatusReason_OptionSetValue = new OptionSetValue((int)value); }
		else this.StatusReason_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statuscode</para>
///</summary>
[AttributeLogicalNameAttribute("statuscode")]
public OptionSetValue StatusReason_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statuscode"); }
	set { this.SetPropertyValue<OptionSetValue>("statuscode", value, "StatusReason_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string StatusReason_Text(IOrganizationService Service)
{
	return this.StatusReason_OptionSetValue.GetOptionSetText(Service, this, "statuscode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string StatusReason_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.StatusReason_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: timezoneruleversionnumber</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("timezoneruleversionnumber")]
public int? TimeZoneRuleVersionNumber
{
	get { return this.GetPropertyValue<int?>("timezoneruleversionnumber"); }
	set { this.SetPropertyValue("timezoneruleversionnumber", (int?)value, (int)-1, (int)2147483647, "TimeZoneRuleVersionNumber"); }
}
///<summary>
///<para>Logical Name: type</para>
///<para>Max Length: 300 characters</para>
///</summary>
[AttributeLogicalNameAttribute("type")]
public string Type
{
	get { return this.GetPropertyValue<string>("type"); }
	set { this.SetPropertyValue("type", value, 300, "Type"); }
}
///<summary>
///<para>Logical Name: utcconversiontimezonecode</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("utcconversiontimezonecode")]
public int? UTCConversionTimeZoneCode
{
	get { return this.GetPropertyValue<int?>("utcconversiontimezonecode"); }
	set { this.SetPropertyValue("utcconversiontimezonecode", (int?)value, (int)-1, (int)2147483647, "UTCConversionTimeZoneCode"); }
}
///<summary>
///<para>Logical Name: yomifirstname</para>
///<para>Max Length: 150 characters</para>
///</summary>
[AttributeLogicalNameAttribute("yomifirstname")]
public string YomiFirstName
{
	get { return this.GetPropertyValue<string>("yomifirstname"); }
	set { this.SetPropertyValue("yomifirstname", value, 150, "YomiFirstName"); }
}
///<summary>
///<para>Logical Name: yomifullname</para>
///<para>Max Length: 450 characters</para>
///</summary>
[AttributeLogicalNameAttribute("yomifullname")]
public string YomiFullName
{
	get { return this.GetPropertyValue<string>("yomifullname"); }
}
///<summary>
///<para>Logical Name: yomilastname</para>
///<para>Max Length: 150 characters</para>
///</summary>
[AttributeLogicalNameAttribute("yomilastname")]
public string YomiLastName
{
	get { return this.GetPropertyValue<string>("yomilastname"); }
	set { this.SetPropertyValue("yomilastname", value, 150, "YomiLastName"); }
}
///<summary>
///<para>Logical Name: yomimiddlename</para>
///<para>Max Length: 150 characters</para>
///</summary>
[AttributeLogicalNameAttribute("yomimiddlename")]
public string YomiMiddleName
{
	get { return this.GetPropertyValue<string>("yomimiddlename"); }
	set { this.SetPropertyValue("yomimiddlename", value, 150, "YomiMiddleName"); }
}


        /// <summary>
/// <para><b>Account (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_account_createdby</para>
/// </summary>
public List<Account> GetAccounts_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Account>(Service, this.Id, "account", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Account (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_account_createdby</para>
/// </summary>
public List<Account> GetAccounts_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Account>(Service, this.Id, "account", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Account (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_account_modifiedby</para>
/// </summary>
public List<Account> GetAccounts_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Account>(Service, this.Id, "account", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>Account (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_account_modifiedby</para>
/// </summary>
public List<Account> GetAccounts_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Account>(Service, this.Id, "account", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>SystemJob (Regarding)</b></para>
/// <para>Schema Name: externalparty_AsyncOperations</para>
/// </summary>
public List<SystemJob> GetSystemJobs_Regarding (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<SystemJob>(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>SystemJob (Regarding)</b></para>
/// <para>Schema Name: externalparty_AsyncOperations</para>
/// </summary>
public List<SystemJob> GetSystemJobs_Regarding (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<SystemJob>(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>BulkDeleteFailure (Name)</b></para>
/// <para>Schema Name: externalparty_BulkDeleteFailures</para>
/// </summary>
public List<BulkDeleteFailure> GetBulkDeleteFailures_Name (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<BulkDeleteFailure>(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>BulkDeleteFailure (Name)</b></para>
/// <para>Schema Name: externalparty_BulkDeleteFailures</para>
/// </summary>
public List<BulkDeleteFailure> GetBulkDeleteFailures_Name (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<BulkDeleteFailure>(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Contact (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_contact_createdby</para>
/// </summary>
public List<Contact> GetContacts_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Contact>(Service, this.Id, "contact", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Contact (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_contact_createdby</para>
/// </summary>
public List<Contact> GetContacts_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Contact>(Service, this.Id, "contact", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Contact (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_contact_modifiedby</para>
/// </summary>
public List<Contact> GetContacts_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Contact>(Service, this.Id, "contact", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>Contact (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_contact_modifiedby</para>
/// </summary>
public List<Contact> GetContacts_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Contact>(Service, this.Id, "contact", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>ExternalPartyItem (External Party)</b></para>
/// <para>Schema Name: externalparty_entries</para>
/// </summary>
public List<ExternalPartyItem> GetExternalPartyItems_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<ExternalPartyItem>(Service, this.Id, "externalpartyitem", "externalpartyid", Columns); }
/// <summary>
/// <para><b>ExternalPartyItem (External Party)</b></para>
/// <para>Schema Name: externalparty_entries</para>
/// </summary>
public List<ExternalPartyItem> GetExternalPartyItems_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<ExternalPartyItem>(Service, this.Id, "externalpartyitem", "externalpartyid", Columns); }
/// <summary>
/// <para><b>@Case (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incident_createdby</para>
/// </summary>
public List<@Case> GetCases_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<@Case>(Service, this.Id, "incident", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>@Case (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incident_createdby</para>
/// </summary>
public List<@Case> GetCases_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<@Case>(Service, this.Id, "incident", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>@Case (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incident_modifiedby</para>
/// </summary>
public List<@Case> GetCases_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<@Case>(Service, this.Id, "incident", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>@Case (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incident_modifiedby</para>
/// </summary>
public List<@Case> GetCases_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<@Case>(Service, this.Id, "incident", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>CaseResolution (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incidentresolution_createdby</para>
/// </summary>
public List<CaseResolution> GetCaseResolutions_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CaseResolution>(Service, this.Id, "incidentresolution", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>CaseResolution (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incidentresolution_createdby</para>
/// </summary>
public List<CaseResolution> GetCaseResolutions_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CaseResolution>(Service, this.Id, "incidentresolution", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>CaseResolution (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incidentresolution_modifiedby</para>
/// </summary>
public List<CaseResolution> GetCaseResolutions_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CaseResolution>(Service, this.Id, "incidentresolution", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>CaseResolution (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_incidentresolution_modifiedby</para>
/// </summary>
public List<CaseResolution> GetCaseResolutions_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<CaseResolution>(Service, this.Id, "incidentresolution", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>OpportunityClose (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_opportunityclose_createdby</para>
/// </summary>
public List<OpportunityClose> GetOpportunityCloseActivities_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OpportunityClose>(Service, this.Id, "opportunityclose", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>OpportunityClose (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_opportunityclose_createdby</para>
/// </summary>
public List<OpportunityClose> GetOpportunityCloseActivities_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OpportunityClose>(Service, this.Id, "opportunityclose", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>OpportunityClose (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_opportunityclose_modifiedby</para>
/// </summary>
public List<OpportunityClose> GetOpportunityCloseActivities_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OpportunityClose>(Service, this.Id, "opportunityclose", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>OpportunityClose (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_opportunityclose_modifiedby</para>
/// </summary>
public List<OpportunityClose> GetOpportunityCloseActivities_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OpportunityClose>(Service, this.Id, "opportunityclose", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>OrderClose (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_orderclose_createdby</para>
/// </summary>
public List<OrderClose> GetOrderCloseActivities_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OrderClose>(Service, this.Id, "orderclose", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>OrderClose (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_orderclose_createdby</para>
/// </summary>
public List<OrderClose> GetOrderCloseActivities_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OrderClose>(Service, this.Id, "orderclose", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>OrderClose (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_orderclose_modifiedby</para>
/// </summary>
public List<OrderClose> GetOrderCloseActivities_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OrderClose>(Service, this.Id, "orderclose", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>OrderClose (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_orderclose_modifiedby</para>
/// </summary>
public List<OrderClose> GetOrderCloseActivities_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<OrderClose>(Service, this.Id, "orderclose", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>PostRegarding (RegardingObjectId)</b></para>
/// <para>Schema Name: externalparty_PostRegardings</para>
/// </summary>
public List<PostRegarding> GetPostRegarding_RegardingObjectId (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<PostRegarding>(Service, this.Id, "postregarding", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>PostRegarding (RegardingObjectId)</b></para>
/// <para>Schema Name: externalparty_PostRegardings</para>
/// </summary>
public List<PostRegarding> GetPostRegarding_RegardingObjectId (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<PostRegarding>(Service, this.Id, "postregarding", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>ProcessSession (Regarding)</b></para>
/// <para>Schema Name: externalparty_ProcessSession</para>
/// </summary>
public List<ProcessSession> GetProcessSessions_Regarding (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<ProcessSession>(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>ProcessSession (Regarding)</b></para>
/// <para>Schema Name: externalparty_ProcessSession</para>
/// </summary>
public List<ProcessSession> GetProcessSessions_Regarding (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<ProcessSession>(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Product (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_product_createdby</para>
/// </summary>
public List<Product> GetProducts_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Product>(Service, this.Id, "product", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Product (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_product_createdby</para>
/// </summary>
public List<Product> GetProducts_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Product>(Service, this.Id, "product", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Product (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_product_modifiedby</para>
/// </summary>
public List<Product> GetProducts_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Product>(Service, this.Id, "product", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>Product (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_product_modifiedby</para>
/// </summary>
public List<Product> GetProducts_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Product>(Service, this.Id, "product", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>QuoteClose (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_quoteclose_createdby</para>
/// </summary>
public List<QuoteClose> GetQuoteCloseActivities_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<QuoteClose>(Service, this.Id, "quoteclose", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>QuoteClose (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_quoteclose_createdby</para>
/// </summary>
public List<QuoteClose> GetQuoteCloseActivities_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<QuoteClose>(Service, this.Id, "quoteclose", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>QuoteClose (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_quoteclose_modifiedby</para>
/// </summary>
public List<QuoteClose> GetQuoteCloseActivities_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<QuoteClose>(Service, this.Id, "quoteclose", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>QuoteClose (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_quoteclose_modifiedby</para>
/// </summary>
public List<QuoteClose> GetQuoteCloseActivities_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<QuoteClose>(Service, this.Id, "quoteclose", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>Subject (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_subject_createdby</para>
/// </summary>
public List<Subject> GetSubjects_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Subject>(Service, this.Id, "subject", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Subject (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_subject_createdby</para>
/// </summary>
public List<Subject> GetSubjects_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Subject>(Service, this.Id, "subject", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Subject (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_subject_modifiedby</para>
/// </summary>
public List<Subject> GetSubjects_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Subject>(Service, this.Id, "subject", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>Subject (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_subject_modifiedby</para>
/// </summary>
public List<Subject> GetSubjects_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Subject>(Service, this.Id, "subject", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>SyncError (Record)</b></para>
/// <para>Schema Name: ExternalParty_SyncErrors</para>
/// </summary>
public List<SyncError> GetSyncErrors_Record (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<SyncError>(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>SyncError (Record)</b></para>
/// <para>Schema Name: ExternalParty_SyncErrors</para>
/// </summary>
public List<SyncError> GetSyncErrors_Record (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<SyncError>(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Unit (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uom_createdby</para>
/// </summary>
public List<Unit> GetUnits_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Unit>(Service, this.Id, "uom", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Unit (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uom_createdby</para>
/// </summary>
public List<Unit> GetUnits_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Unit>(Service, this.Id, "uom", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>Unit (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uom_modifiedby</para>
/// </summary>
public List<Unit> GetUnits_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Unit>(Service, this.Id, "uom", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>Unit (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uom_modifiedby</para>
/// </summary>
public List<Unit> GetUnits_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Unit>(Service, this.Id, "uom", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>UnitGroup (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uomschedule_createdby</para>
/// </summary>
public List<UnitGroup> GetUnitGroups_CreatedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<UnitGroup>(Service, this.Id, "uomschedule", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>UnitGroup (Created By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uomschedule_createdby</para>
/// </summary>
public List<UnitGroup> GetUnitGroups_CreatedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<UnitGroup>(Service, this.Id, "uomschedule", "createdbyexternalparty", Columns); }
/// <summary>
/// <para><b>UnitGroup (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uomschedule_modifiedby</para>
/// </summary>
public List<UnitGroup> GetUnitGroups_ModifiedBy_ExternalParty (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<UnitGroup>(Service, this.Id, "uomschedule", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>UnitGroup (Modified By (External Party))</b></para>
/// <para>Schema Name: lk_externalparty_uomschedule_modifiedby</para>
/// </summary>
public List<UnitGroup> GetUnitGroups_ModifiedBy_ExternalParty (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<UnitGroup>(Service, this.Id, "uomschedule", "modifiedbyexternalparty", Columns); }
/// <summary>
/// <para><b>UserEntityInstanceData (Object Id)</b></para>
/// <para>Schema Name: externalparty_UserEntityInstanceDatas</para>
/// </summary>
public List<UserEntityInstanceData> GetUserEntityInstanceData_ObjectId (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<UserEntityInstanceData>(Service, this.Id, "userentityinstancedata", "objectid", Columns); }
/// <summary>
/// <para><b>UserEntityInstanceData (Object Id)</b></para>
/// <para>Schema Name: externalparty_UserEntityInstanceDatas</para>
/// </summary>
public List<UserEntityInstanceData> GetUserEntityInstanceData_ObjectId (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<UserEntityInstanceData>(Service, this.Id, "userentityinstancedata", "objectid", Columns); }


        

        

        public enum eStatus
{
	///<summary><para>Enabled</para>
	///<para>Value = 0</para></summary>
	[Description("Enabled")]
	Enabled = 0, 
	///<summary><para>Disabled</para>
	///<para>Value = 1</para></summary>
	[Description("Disabled")]
	Disabled = 1
}
public enum eStatusReason
{
	///<summary><para>Enabled</para>
	///<para>Value = 1</para></summary>
	[Description("Enabled")]
	Enabled_Enabled = 1, 
	///<summary><para>Disabled</para>
	///<para>Value = 2</para></summary>
	[Description("Disabled")]
	Disabled_Disabled = 2
}
public void SetState(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	Service.SetState(this, (int)State, (int)Status);
}
public async System.Threading.Tasks.Task SetStateAsync(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	 await Service.SetStateAsync(this, (int)State, (int)Status);
}


        public static class Properties
{
	/// <summary><para>createdonbehalfbyyominame</para>
	/// <para>createdonbehalfbyyominame</para></summary>
	public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
	/// <summary><para>owneridname</para>
	/// <para>owneridname</para></summary>
	public const string OwnerIdName = "owneridname";
	/// <summary><para>createdbyyominame</para>
	/// <para>createdbyyominame</para></summary>
	public const string CreatedByYomiName = "createdbyyominame";
	/// <summary><para>modifiedbyname</para>
	/// <para>modifiedbyname</para></summary>
	public const string ModifiedByName = "modifiedbyname";
	/// <summary><para>modifiedbyyominame</para>
	/// <para>modifiedbyyominame</para></summary>
	public const string ModifiedByYomiName = "modifiedbyyominame";
	/// <summary><para>owneridtype</para>
	/// <para>owneridtype</para></summary>
	public const string OwnerIdType = "owneridtype";
	/// <summary><para>owneridyominame</para>
	/// <para>owneridyominame</para></summary>
	public const string OwnerIdYomiName = "owneridyominame";
	/// <summary><para>modifiedonbehalfbyyominame</para>
	/// <para>modifiedonbehalfbyyominame</para></summary>
	public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
	/// <summary><para>createdbyname</para>
	/// <para>createdbyname</para></summary>
	public const string CreatedByName = "createdbyname";
	/// <summary><para>createdonbehalfbyname</para>
	/// <para>createdonbehalfbyname</para></summary>
	public const string CreatedOnBehalfByName = "createdonbehalfbyname";
	/// <summary><para>modifiedonbehalfbyname</para>
	/// <para>modifiedonbehalfbyname</para></summary>
	public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
	/// <summary><para>versionnumber</para>
	/// <para>versionnumber</para></summary>
	public const string VersionNumber = "versionnumber";
	/// <summary><para>transactioncurrencyidname</para>
	/// <para>transactioncurrencyidname</para></summary>
	public const string TransactionCurrencyIdName = "transactioncurrencyidname";
	/// <summary><para>Correlation Key</para>
	/// <para>correlationkey</para></summary>
	public const string CorrelationKey = "correlationkey";
	/// <summary><para>Created By</para>
	/// <para>createdby</para></summary>
	public const string CreatedBy = "createdby";
	/// <summary><para>Created By (Delegate)</para>
	/// <para>createdonbehalfby</para></summary>
	public const string CreatedBy_Delegate = "createdonbehalfby";
	/// <summary><para>Created On</para>
	/// <para>createdon</para></summary>
	public const string CreatedOn = "createdon";
	/// <summary><para>Currency</para>
	/// <para>transactioncurrencyid</para></summary>
	public const string Currency = "transactioncurrencyid";
	/// <summary><para>Email Address</para>
	/// <para>emailaddress</para></summary>
	public const string EmailAddress = "emailaddress";
	/// <summary><para>ExchangeRate</para>
	/// <para>exchangerate</para></summary>
	public const string ExchangeRate = "exchangerate";
	/// <summary><para>External Party</para>
	/// <para>externalpartyid</para></summary>
	public const string ExternalPartyId = "externalpartyid";
	/// <summary><para>External Party Unique Id</para>
	/// <para>externalpartyidunique</para></summary>
	public const string ExternalPartyUniqueId = "externalpartyidunique";
	/// <summary><para>First Name</para>
	/// <para>firstname</para></summary>
	public const string FirstName = "firstname";
	/// <summary><para>Full Name</para>
	/// <para>fullname</para></summary>
	public const string FullName = "fullname";
	/// <summary><para>Import Sequence Number</para>
	/// <para>importsequencenumber</para></summary>
	public const string ImportSequenceNumber = "importsequencenumber";
	/// <summary><para>Last Disabled On</para>
	/// <para>lastdisabledon</para></summary>
	public const string LastDisabledOn = "lastdisabledon";
	/// <summary><para>Last Enabled On</para>
	/// <para>lastenabledon</para></summary>
	public const string LastEnabledOn = "lastenabledon";
	/// <summary><para>Last Name</para>
	/// <para>lastname</para></summary>
	public const string LastName = "lastname";
	/// <summary><para>Middle Name</para>
	/// <para>middlename</para></summary>
	public const string MiddleName = "middlename";
	/// <summary><para>Modified By</para>
	/// <para>modifiedby</para></summary>
	public const string ModifiedBy = "modifiedby";
	/// <summary><para>Modified By (Delegate)</para>
	/// <para>modifiedonbehalfby</para></summary>
	public const string ModifiedBy_Delegate = "modifiedonbehalfby";
	/// <summary><para>Modified On</para>
	/// <para>modifiedon</para></summary>
	public const string ModifiedOn = "modifiedon";
	/// <summary><para>Owner</para>
	/// <para>ownerid</para></summary>
	public const string Owner = "ownerid";
	/// <summary><para>Owning Business Unit</para>
	/// <para>owningbusinessunit</para></summary>
	public const string OwningBusinessUnit = "owningbusinessunit";
	/// <summary><para>Owning Team</para>
	/// <para>owningteam</para></summary>
	public const string OwningTeam = "owningteam";
	/// <summary><para>Owning User</para>
	/// <para>owninguser</para></summary>
	public const string OwningUser = "owninguser";
	/// <summary><para>Record Created On</para>
	/// <para>overriddencreatedon</para></summary>
	public const string RecordCreatedOn = "overriddencreatedon";
	/// <summary><para>Status</para>
	/// <para>statecode</para></summary>
	public const string Status = "statecode";
	/// <summary><para>Status Reason</para>
	/// <para>statuscode</para></summary>
	public const string StatusReason = "statuscode";
	/// <summary><para>Time Zone Rule Version Number</para>
	/// <para>timezoneruleversionnumber</para></summary>
	public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
	/// <summary><para>Type</para>
	/// <para>type</para></summary>
	public const string Type = "type";
	/// <summary><para>UTC Conversion Time Zone Code</para>
	/// <para>utcconversiontimezonecode</para></summary>
	public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
	/// <summary><para>Yomi First Name</para>
	/// <para>yomifirstname</para></summary>
	public const string YomiFirstName = "yomifirstname";
	/// <summary><para>Yomi Full Name</para>
	/// <para>yomifullname</para></summary>
	public const string YomiFullName = "yomifullname";
	/// <summary><para>Yomi Last Name</para>
	/// <para>yomilastname</para></summary>
	public const string YomiLastName = "yomilastname";
	/// <summary><para>Yomi Middle Name</para>
	/// <para>yomimiddlename</para></summary>
	public const string YomiMiddleName = "yomimiddlename";
}

    }
}
