// <auto-generated />
using .ProxyClasses;
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.Threading.Tasks;
using System.ComponentModel;

namespace ProxyClasses
{
    [EntityLogicalNameAttribute("knowledgearticlescategories")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XrmToolkit", "4.0")]
    public partial class KnowledgeArticleCategory : BaseProxyClass
    {
        public new const string LogicalName = "knowledgearticlescategories";
        public const int ObjectTypeCode = 9960;
        public const string PrimaryIdAttribute = "knowledgearticlecategoryid";
        public const string PrimaryNameAttribute = "";
        
        static KnowledgeArticleCategory()
        {
            BaseProxyClass.RegisterProxyType(typeof(KnowledgeArticleCategory), "knowledgearticlescategories");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public KnowledgeArticleCategory() : base(new Entity("knowledgearticlescategories")) { }
        public KnowledgeArticleCategory(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<KnowledgeArticleCategory>(); }
        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }
        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }
        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }
        private static Dictionary<string, eNumberOptions> _numberOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }

        ///<summary>
///<para>Logical Name: categoryid</para>
///</summary>
[AttributeLogicalNameAttribute("categoryid")]
public Guid CategoryId
{
	get { return this.GetPropertyValue<Guid>("categoryid"); }
}
///<summary>
///<para>Logical Name: versionnumber</para>
///</summary>
[AttributeLogicalNameAttribute("versionnumber")]
public int? VersionNumber
{
	get { return this.GetPropertyValue<int?>("versionnumber"); }
}
///<summary>
///<para>Key Property (Uniqueidentifier)</para>
///<para>Logical Name: knowledgearticlecategoryid</para>
///</summary>
[AttributeLogicalNameAttribute("knowledgearticlecategoryid")]
public Guid KnowledgeArticleCategoryId
{
	get
	{
		return this.Id;
	}
	set
	{
		this.Id = value;
	}
}
///<summary>
///<para>Logical Name: knowledgearticleid</para>
///</summary>
[AttributeLogicalNameAttribute("knowledgearticleid")]
public Guid KnowledgeArticleId
{
	get { return this.GetPropertyValue<Guid>("knowledgearticleid"); }
}


        

        /// <summary>
/// <para>Related Entity: <b>Knowledge Article</b></para>
/// <para>N:N Relationship</para>
/// <para>Schema Name: knowledgearticle_category</para>
/// </summary>
public List<KnowledgeArticle> GetKnowledgeArticles (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedManyToManyEntities<KnowledgeArticle>(Service, this, "knowledgearticlescategories", "knowledgearticlecategoryid", "knowledgearticle", "knowledgearticleid", "knowledgearticlescategories", "categoryid", "knowledgearticleid", Columns); }
public List<KnowledgeArticle> GetKnowledgeArticles (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedManyToManyEntities<KnowledgeArticle>(Service, this, "knowledgearticlescategories", "knowledgearticlecategoryid", "knowledgearticle", "knowledgearticleid", "knowledgearticlescategories", "categoryid", "knowledgearticleid", Columns); }
public void RelateKnowledgeArticles (IOrganizationService Service, params Entity[] Items) { Service.RelateEntities(this, "knowledgearticle_category", Items); }
public void RelateKnowledgeArticles (IOrganizationService Service, params EntityReference[] Items) { Service.RelateEntities(this, "knowledgearticle_category", Items); }
public void UnRelateKnowledgeArticles (IOrganizationService Service, params Entity[] Items) { Service.UnRelateEntities(this, "knowledgearticle_category", Items); }
public void UnRelateKnowledgeArticles (IOrganizationService Service, params EntityReference[] Items) { Service.UnRelateEntities(this, "knowledgearticle_category", Items); }


        

        

        public static class Properties
{
	/// <summary><para>categoryid</para>
	/// <para>categoryid</para></summary>
	public const string CategoryId = "categoryid";
	/// <summary><para>versionnumber</para>
	/// <para>versionnumber</para></summary>
	public const string VersionNumber = "versionnumber";
	/// <summary><para>knowledgearticlecategoryid</para>
	/// <para>knowledgearticlecategoryid</para></summary>
	public const string KnowledgeArticleCategoryId = "knowledgearticlecategoryid";
	/// <summary><para>knowledgearticleid</para>
	/// <para>knowledgearticleid</para></summary>
	public const string KnowledgeArticleId = "knowledgearticleid";
}

    }
}
